# For production use, this will get the image from Docker Hub instead of building it locally.
version: "3.8"

services:
  ririko-bot:
    image: ririkoai/ririkobot:latest
    container_name: ririko-bot
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: production
      APP_PORT: 3000
      DISCORD_BOT_TOKEN: your_discord_bot_token
      DISCORD_APPLICATION_ID: your_discord_application_id
      BOT_OWNER_ID: your_discord_user_id
      DEFAULT_PREFIX: "!"
      DATABASE_TYPE: better-sqlite3
      DATABASE_NAME: /app/data/ririko.db
    restart: unless-stopped
