version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ririkobot:latest
    depends_on:
      - mongodb
    restart: always
    #    environment:
    #      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
volumes:
  mongo-data: