version: "3"

services:
  ## MongoDB Server
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  ## Ririko Bot App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ririkoai/ririkobot:latest
    depends_on:
      - mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    volumes:
      - app-data:/opt/app/data
      - ./config:/opt/app/config
      - ./logs:/opt/app/logs

volumes:
  mongo-data:
  app-data: