FROM node:22-slim

# Install system dependencies for canvas and better-sqlite3
RUN apt-get update && apt-get install -y \
    build-essential \
    libnode108 \
    python3 \
    git \
    pkg-config \
    libcairo2-dev \
    libjpeg-dev \
    libpango1.0-dev \
    libgif-dev \
    librsvg2-dev \
    libsqlite3-dev \
    sqlite3 \
    node-gyp \
    g++ \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# Install project dependencies
RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]