version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install --dev
          name: Install dev dependencies
      - run:
          command: cp config.example.ts config.ts
          name: Copy configuration file
      - run:
          command: npm run test
          name: Test

workflows:
  test_my_app:
    jobs:
      - build_and_test
