version: 2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: install-npm-dev
          command: npm install --dev
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test
