version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@4.0.1

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install --include=dev
          name: Install dev dependencies
      - run:
          command: npm run build
          name: Build
      - run:
          command: npm run test:ci
          name: Test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
      - run:
          command: rm -rf ./coverage/clover.xml
          name: Remove clover.xml
      - codecov/upload:
          file: './coverage/lcov.info'

workflows:
  test_my_app:
    jobs:
      - build_and_test