export const ErrorCode = {
  // System & Configuration
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth & Permissions
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Resource Lifecycle
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Database & Storage
  DATABASE_ERROR: 'DATABASE_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',

  // Rate Limiting & Cooldowns
  RATE_LIMITED: 'RATE_LIMITED',
  COOLDOWN_ACTIVE: 'COOLDOWN_ACTIVE',

  // External APIs & Network
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',

  // Domain Business Rules
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  ITEM_NOT_TRADEABLE: 'ITEM_NOT_TRADEABLE',

  // Voice & Audio
  VOICE_CONNECTION_ERROR: 'VOICE_CONNECTION_ERROR',
  EXTRACTOR_ERROR: 'EXTRACTOR_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
