module.exports.sfw = [
  {
    tickle: "/img/tickle",
    slap: "/img/slap",
    poke: "/img/poke",
    pat: "/img/pat",
    neko: "/img/neko",
    meow: "/img/meow",
    lizard: "/img/lizard",
    kiss: "/img/kiss",
    hug: "/img/hug",
    foxGirl: "/img/fox_girl",
    feed: "/img/feed",
    cuddle: "/img/cuddle",
    why: "/why",
    catText: "/cat",
    OwOify: "/owoify",
    Ball8: "/8ball",
    fact: "/fact",
    nekoGif: "/img/ngif",
    kemonomimi: "/img/kemonomimi",
    holo: "/img/holo",
    smug: "/img/smug",
    baka: "/img/baka",
    woof: "/img/woof",
    spoiler: "/spoiler",
    wallpaper: "/img/wallpaper",
    goose: "/img/goose",
    gecg: "/img/gecg",
    avatar: "/img/avatar",
    waifu: "/img/waifu",
  },
];

module.exports.sfwAZ = `avatar baka Ball8 catText cuddle fact feed foxGirl gecg goose holo hug kemonomimi kiss lizard meow neko nekoGif OwOify pat poke slap smug spoiler tickle waifu wallpaper why woof`;
