import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const heightStories = [
  story(
    'the-windmill-sky',
    'The Windmill Sky',
    'Keep a floating granary from drifting into a storm.',
    'LIGHTNING',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Bread Above the Clouds',
        'The sky island’s windmills turn in different directions. A loaded grain platform swings toward the storm, and the mill keeper has vanished beneath its sails.',
        [
          go('Climb the main windmill', 'sails'),
          go('Search the grain platform', 'grain'),
          pay('Hire a sky skiff (50 credits)', 50, 'skiff'),
        ],
      ),
      d(
        'skiff',
        2,
        'A Clear Approach',
        'The skiff lifts you above the torn sails. Its pilot rescues the keeper while you choose between the exposed steering balcony and the cloud anchor below.',
        [
          go('Board the steering balcony', 'helm'),
          go('Secure the anchor from the skiff', 'anchor', { rewards: { energy: 3 } }),
        ],
      ),
      d(
        'sails',
        2,
        'A Knot in the Wind',
        'The keeper hangs from a torn sail, holding the island’s steering cord. Releasing it will save his hands but let the storm choose the island’s course.',
        [
          stat('Pull the keeper onto the balcony', 'attack', 140, 'helm', 'anchor'),
          go('Cut the cord and catch him below', 'anchor'),
        ],
      ),
      d(
        'grain',
        2,
        'The Lighter Cargo',
        'The grain platform is chained to an old cloud anchor. Its winch can steady the island, but a flock of storm birds has nested across the controls.',
        [
          check('Guide the birds with a harmless spark', 'LIGHTNING', 0.6, 'helm', 'anchor'),
          go('Reach the anchor from the underside', 'anchor'),
        ],
      ),
      d(
        'helm',
        3,
        'A Course Through Blue',
        'The steering mill answers again. A village below needs the grain, while a wealthy skyship offers to tow the island in exchange for half the harvest.',
        [
          go('Steer toward the hungry village', 'village'),
          go('Signal the skyship for a tow', 'tow'),
        ],
      ),
      d(
        'anchor',
        3,
        'The Old Cloud Anchor',
        'The anchor can hold until the storm passes if the platform is lightened. You can lower the grain to the village or sell it to the nearby skyship.',
        [
          go('Lower grain by the village ropes', 'village'),
          go('Hoist the skyship’s trade flag', 'tow'),
        ],
      ),
      d(
        'village',
        4,
        'One Last Rope',
        'The grain reaches the village, but the last rope still binds it to the drifting island. Cutting it saves the harvest; reeling it in could bring the village’s reward chest aboard.',
        [
          go('Cut the rope and protect the harvest', 'fed'),
          check('Reel in the reward chest before cutting', 'LIGHTNING', 0.5, 'towed', 'drift'),
        ],
      ),
      d(
        'tow',
        4,
        'Terms Above the Clouds',
        'The skyship captain demands half the grain or ownership of the steering mill. The keeper would rather lose a season’s harvest than the island’s freedom.',
        [
          go('Trade half the grain for safe passage', 'towed'),
          go('Refuse the tow and lower the grain', 'fed'),
        ],
      ),
      e(
        'fed',
        'A Harvest Lands',
        'The island settles above clear skies while the village fills its granaries. A basket rises on a kite with your payment and the first warm bread of the season.',
        'SUCCESS',
        reward(230, 140),
      ),
      e(
        'towed',
        'Safe Moorings',
        'The windmills reach a sheltered cloud bank. The keeper pays you from the remaining trade proceeds, already planning stronger ropes for the next harvest.',
        'MIXED',
        reward(310, 90, 20),
      ),
      e(
        'drift',
        'A Chest in the Clouds',
        'The rope snaps before the chest reaches you. The keeper hauls you onto the balcony as the last coins vanish into the cloud below.',
        'FAILURE',
        { rewards: { xp: 70 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-forgotten-observatory',
    'The Forgotten Observatory',
    'Finish an astronomer’s warning before a comet passes unnoticed.',
    'LIGHT',
    'BALANCED',
    [
      d(
        'root',
        1,
        'A Telescope Still Turning',
        'The abandoned observatory tracks a comet nobody else can see. Its clockwork assistant insists that the astronomer will return before tonight’s alarm.',
        [
          go('Examine the astronomer’s notebook', 'notes'),
          go('Inspect the telescope mount', 'mount'),
        ],
      ),
      d(
        'notes',
        2,
        'A Warning in the Margin',
        'The notebook predicts falling fragments near the town. The astronomer left to warn its council, but the observatory’s proof remained locked beneath his star map.',
        [
          go('Reconstruct the map from his notes', 'proof'),
          go('Take the warning straight to the assistant', 'alarm'),
        ],
      ),
      d(
        'mount',
        2,
        'Dust on the Lens',
        'The telescope’s lens is cloudy with years of dust. Its mount has a second position aimed at the town’s signal tower rather than the sky.',
        [
          check('Focus the hidden comet’s light', 'LIGHT', 0.65, 'proof', 'alarm'),
          go('Aim toward the signal tower', 'alarm'),
        ],
      ),
      d(
        'proof',
        3,
        'The Town in the Path',
        'The restored map proves the fragments will strike the empty quarry if the council clears its workers. A private collector offers to buy the prediction instead.',
        [go('Prepare a public warning', 'signal'), go('Negotiate with the collector', 'collector')],
      ),
      d(
        'alarm',
        3,
        'A Machine Kept Waiting',
        'The assistant has delayed every alarm because its master never returned. The astronomer’s last letter appoints the machine as keeper, but it has never opened the envelope.',
        [
          go('Read the appointment aloud', 'signal'),
          go('Ask the collector for a replacement keeper', 'collector'),
        ],
      ),
      d(
        'signal',
        4,
        'A Light the Town Can See',
        'The assistant winds the signal mechanism. It can send a plain evacuation flash or project the full comet map across the clouds.',
        [
          go('Flash the quarry evacuation signal', 'warned'),
          check('Project the complete map above town', 'LIGHT', 0.6, 'discovery', 'clouded'),
        ],
      ),
      d(
        'collector',
        4,
        'Who Owns a Warning',
        'The collector offers generous payment if only his miners learn where the fragments will fall. The assistant waits beside the public signal lever.',
        [
          go('Send the public warning first', 'warned'),
          go('Sell the map after clearing the quarry', 'discovery'),
        ],
      ),
      e(
        'warned',
        'A Keeper’s First Night',
        'The quarry stands empty when the fragments arrive. The council sends a reward to the observatory, and the assistant finally changes the name on its duty roster.',
        'SUCCESS',
        reward(240, 150),
      ),
      e(
        'discovery',
        'A Comet Remembered',
        'The warning reaches the workers and the discovery reaches every collector in town. Your payment helps put a living observer beside the clockwork keeper again.',
        'SUCCESS',
        reward(330, 110, 20),
      ),
      e(
        'clouded',
        'Clouds Before the Comet',
        'The projection scatters across thick cloud. You carry the warning down the hill on foot, arriving breathless while the assistant rings every bell it can find.',
        'MIXED',
        { rewards: { credits: { min: 100, max: 100 }, xp: 100 }, penalties: { energy: 3 } },
      ),
    ],
  ),
  story(
    'the-silk-labyrinth',
    'The Silk Labyrinth',
    'Find a missing weaver inside a maze that repairs itself.',
    'SHADOW',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'A Thread Across the Door',
        'Silver silk blocks the cavern road. The village weaver entered to negotiate safe passage; her spool now hangs outside, unwinding into the dark.',
        [go('Follow the weaver’s thread', 'thread'), go('Watch how the webs are repaired', 'web')],
      ),
      d(
        'thread',
        2,
        'Knots for a Message',
        'Three knots mark danger, two mark water, and one marks a meeting. The thread divides beside a cocoon large enough to hold a person.',
        [go('Follow the single-knot strand', 'weaver'), go('Open the breathing cocoon', 'brood')],
      ),
      d(
        'web',
        2,
        'The Repairing Hands',
        'Small spiders seal every cut made by travelers. They recoil from the old road’s torch marks, but leave a narrow path wherever your shadow falls.',
        [
          check('Walk the quiet shadow path', 'SHADOW', 0.6, 'weaver', 'brood'),
          go('Follow the spiders carrying fresh silk', 'brood'),
        ],
      ),
      d(
        'weaver',
        3,
        'A Loom Between Peoples',
        'The weaver is teaching the brood to spin cloth without closing the road. Their queen asks for a permanent bridge that travelers will not burn.',
        [
          go('Design a marked silk bridge', 'bridge'),
          go('Offer a toll agreement for passage', 'toll'),
        ],
      ),
      d(
        'brood',
        3,
        'What the Cocoon Held',
        'The cocoon shelters injured travelers from falling stone. The queen has been repairing the road itself, unaware that her walls trap the people she protects.',
        [
          go('Show her how to leave an open bridge', 'bridge'),
          go('Negotiate a guided passage toll', 'toll'),
        ],
      ),
      d(
        'bridge',
        4,
        'The First Crossing',
        'The new bridge stretches over the chasm. Testing it with the weaver will earn the queen’s trust; taking a length of royal silk would earn far more in town.',
        [
          go('Cross beside the weaver', 'passage'),
          check('Harvest spare royal silk safely', 'SHADOW', 0.45, 'silk', 'tangle'),
        ],
      ),
      d(
        'toll',
        4,
        'A Fair Thread',
        'The queen asks for one spool per wagon. A merchant suggests charging travelers much more and keeping the difference, while the weaver waits to record the agreement.',
        [
          go('Record the queen’s fair toll', 'passage'),
          go('Sell a private guide contract', 'silk'),
        ],
      ),
      e(
        'passage',
        'A Road Held Together',
        'Travelers cross beneath silk banners showing a single knot. The village pays you for reopening the route, and the weaver leaves her first finished cloth at the queen’s feet.',
        'SUCCESS',
        reward(270, 150, 20),
      ),
      e(
        'silk',
        'Silver by the Spool',
        'You return with a valuable interest in the silk road. The weaver still watches the first travelers carefully, hoping the bargain will survive its new price.',
        'MIXED',
        reward(390, 80, 35),
      ),
      e(
        'tangle',
        'Caught in Kindness',
        'A loose strand folds the bridge around you. The brood cuts you free gently, then spends the rest of the day repairing the damage while you recover on the road.',
        'FAILURE',
        { rewards: { xp: 80 }, penalties: { energy: 5 } },
      ),
    ],
  ),
  story(
    'the-honey-citadel',
    'The Honey Citadel',
    'Uncover why a honey kingdom’s workers have stopped singing.',
    'EARTH',
    'SAFE',
    [
      d(
        'root',
        1,
        'A Silent Hive',
        'The honey citadel’s gates stand open, but no worker song fills the tree. Its steward claims a royal theft has halted production; the gardens below are full of waiting bees.',
        [
          go('Speak with the garden workers', 'garden'),
          go('Inspect the royal honey vault', 'vault'),
        ],
      ),
      d(
        'garden',
        2,
        'Flowers Beyond the Wall',
        'The workers want the western gate opened so they can reach new flowers. The steward insists that unfamiliar pollen will spoil the queen’s favorite honey.',
        [
          go('Collect samples from the western flowers', 'pollen'),
          go('Ask to speak directly with the queen', 'queen'),
        ],
      ),
      d(
        'vault',
        2,
        'An Empty Royal Jar',
        'The missing honey jar sits behind an unopened petition. The queen has been giving her own share to exhausted workers while the steward reports record harvests.',
        [
          go('Carry the petition to the queen', 'queen'),
          go('Compare the jars with garden pollen', 'pollen'),
        ],
      ),
      d(
        'pollen',
        3,
        'A Different Sweetness',
        'The western flowers produce darker, stronger honey. It could feed the entire hive, though it will change the royal recipe the merchants expect.',
        [
          go('Prepare a tasting for the court', 'tasting'),
          go('Find a buyer for the new honey', 'market'),
        ],
      ),
      d(
        'queen',
        3,
        'The Petition Read',
        'The queen asks you to bring both workers and steward to her table. The steward offers to fund a market expedition if the disagreement stays outside the court.',
        [
          go('Bring everyone to the queen’s table', 'tasting'),
          go('Arrange the market expedition', 'market'),
        ],
      ),
      d(
        'tasting',
        4,
        'The First Spoon',
        'The steward refuses the darker honey until someone important tastes it. The queen sets down her crown and asks a worker to share the first spoon.',
        [
          go('Open the western gate together', 'song'),
          go('Reserve a special blend for the merchants', 'blend'),
        ],
      ),
      d(
        'market',
        4,
        'A New Recipe’s Price',
        'A merchant offers a generous first order. Filling it immediately would leave the exhausted workers with another night’s labor, while a smaller shipment could wait for morning.',
        [
          go('Send a smaller shipment after rest', 'song'),
          check('Organize a careful one-night harvest', 'EARTH', 0.65, 'blend', 'sticky'),
        ],
      ),
      e(
        'song',
        'A Wider Garden',
        'The western gate opens and the worker song returns. The queen pays you from her ceremonial fund, then joins the gardeners in planting flowers nobody has named yet.',
        'SUCCESS',
        reward(180, 150, 15),
      ),
      e(
        'blend',
        'A Taste Worth Keeping',
        'The first dark honey sells well enough to repair the hive. You receive a trade bonus while the queen makes sure the workers’ next day begins with rest.',
        'SUCCESS',
        reward(270, 90),
      ),
      e(
        'sticky',
        'Tomorrow’s Shipment',
        'A tired cart tips into the loading gate. You help clean honey from the hinges until dawn, earning a modest wage and a very firm lesson about rest.',
        'MIXED',
        reward(70, 90),
      ),
    ],
  ),
  story(
    'the-ghost-regatta',
    'The Ghost Regatta',
    'Race spectral boats whose captains disagree about the finish line.',
    'WATER',
    'BALANCED',
    [
      d(
        'root',
        1,
        'The Race That Never Docked',
        'Ghost ships gather beneath the harbor moon. The starter offers you a boat and a place in a regatta that has circled the bay for a hundred years.',
        [
          go('Speak with the last-place captain', 'captain'),
          go('Inspect the moving finish buoy', 'buoy'),
        ],
      ),
      d(
        'captain',
        2,
        'A Race for Someone Else',
        'The captain always turns back to rescue a rival who falls overboard. He cannot remember whether the race began before or after the rival drowned.',
        [
          go('Join his rescue route', 'rescue'),
          go('Study the captain’s original race chart', 'chart'),
        ],
      ),
      d(
        'buoy',
        2,
        'A Finish That Drifts',
        'The buoy moves away from whichever boat leads. Beneath it, an old harbor chain links the race to a bell that has never announced a winner.',
        [
          check('Steady the buoy against the current', 'WATER', 0.6, 'chart', 'rescue'),
          go('Follow the chain toward the fallen sailor', 'rescue'),
        ],
      ),
      d(
        'rescue',
        3,
        'A Hand Above the Water',
        'The rival rises beside your boat. He remembers sacrificing his lead to save the captain, and asks you to end the argument about who owes whom a rescue.',
        [
          go('Bring both captains to the finish together', 'together'),
          go('Take the rival aboard and pursue the lead', 'race'),
        ],
      ),
      d(
        'chart',
        3,
        'The Original Finish',
        'The chart places the finish at the harbor steps, not the buoy. The starter has moved it each year to keep his last happy night from ending.',
        [
          go('Invite the fleet to finish at the steps', 'together'),
          go('Steer for the old finish before the fleet', 'race'),
        ],
      ),
      d(
        'together',
        4,
        'A Bell for Every Boat',
        'The fleet reaches the steps abreast. The starter offers you the winner’s purse if you name a champion; the bell rope hangs within reach.',
        [
          go('Ring for the entire fleet', 'harbor'),
          go('Name the two rescuers joint champions', 'prize'),
        ],
      ),
      d(
        'race',
        4,
        'The Last Tack',
        'The old finish lies beyond a cross-current. Your ghostly passenger can guide a daring tack, or you can wait for the rescuing captain and arrive together.',
        [
          check('Take the daring final tack', 'WATER', 0.55, 'prize', 'capsized'),
          go('Wait and finish with the captain', 'harbor'),
        ],
      ),
      e(
        'harbor',
        'Boats at Rest',
        'The harbor bell rings until every boat has docked. The starter gives you the old race fund, and the captains walk ashore without looking back at the tide.',
        'SUCCESS',
        reward(250, 150),
      ),
      e(
        'prize',
        'A Race Finally Won',
        'The crowd of ghosts cheers a winner it can remember. The prize chest becomes solid in your boat as the sails dissolve into ordinary moonlight.',
        'SUCCESS',
        reward(340, 100, 20),
      ),
      e(
        'capsized',
        'A Familiar Rescue',
        'The cross-current overturns your boat. Both captains haul you aboard before laughing at the shape of the old story; you reach shore wet, alive, and without the prize.',
        'MIXED',
        { rewards: { xp: 100 }, penalties: { energy: 3 } },
      ),
    ],
  ),
];
