import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const wonderStories = [
  story(
    'the-clockwork-orchard',
    'The Clockwork Orchard',
    'Help a mechanical orchard decide who deserves its last harvest.',
    'LIGHTNING',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Fruit That Ticks',
        'Brass apples strike midnight in a greenhouse at noon. The caretaker begs you to stop the harvest engine before it shakes the village apart.',
        [go('Inspect the irrigation gears', 'gears'), go('Listen to the oldest tree', 'tree')],
      ),
      d(
        'gears',
        2,
        'A Stolen Spring',
        'The irrigation wheel is missing its spring. A magpie has woven it into a nest above the copper branches; a merchant offers a replacement.',
        [
          check('Coax the magpie with sparks', 'LIGHTNING', 0.55, 'water', 'drought'),
          pay('Buy a spring (60 credits)', 60, 'water'),
          go('Turn the wheel by hand', 'drought'),
        ],
      ),
      d(
        'tree',
        2,
        'The Orchard Remembers',
        'The oldest tree taps a warning: the engine feeds the manor first. A buried pipe could carry the last water to the village instead.',
        [go('Open the village pipe', 'water'), go('Follow the manor pipe', 'drought')],
      ),
      d(
        'water',
        3,
        'One Last Harvest',
        'Water reaches the roots. Golden fruit begins to ripen, but the engine demands a destination before it will release the crop.',
        [
          go('Set the village as recipient', 'basket'),
          go('Reserve the fruit for repairs', 'engine'),
        ],
      ),
      d(
        'drought',
        3,
        'Dry Teeth',
        'The wheel grinds against empty pipes. The manor reservoir is sealed by an old ownership plate, while a hand crank could produce one small basket.',
        [
          stat('Break the reservoir seal', 'attack', 150, 'basket', 'engine'),
          go('Work the hand crank', 'engine'),
        ],
      ),
      d(
        'basket',
        4,
        'The First Apple',
        'A basket rolls toward the village gate. Its last apple holds the master winding key; keeping it would let you sell the orchard to the manor.',
        [
          go('Plant the key beneath the oldest tree', 'freed'),
          go('Sell the key to the manor', 'sold'),
        ],
      ),
      d(
        'engine',
        4,
        'The Final Winding',
        'The engine has one winding left. It can grow a seed for next year or force a harvest that will strip its gears.',
        [
          go('Save a seed for spring', 'freed'),
          check('Force the final harvest', 'LIGHTNING', 0.45, 'sold', 'broken'),
        ],
      ),
      e(
        'freed',
        'An Orchard of Its Own',
        'The trees stop ticking in unison. A child receives the first apple grown on their own time, and the caretaker shares the repair fund with you.',
        'SUCCESS',
        reward(220, 120, 20),
      ),
      e(
        'sold',
        'A Golden Receipt',
        'A manor cart collects the fruit and the key. Your purse is heavier, but every tree begins ticking to the same distant bell.',
        'MIXED',
        reward(340, 60),
      ),
      e(
        'broken',
        'Spring Must Wait',
        'The last gear splits. You leave the caretaker a safe, silent greenhouse and carry a handful of salvage back through the village.',
        'FAILURE',
        { rewards: { dust: 25, xp: 40 }, penalties: { energy: 3 } },
      ),
    ],
  ),
  story(
    'the-lantern-marsh',
    'The Lantern Marsh',
    'Guide a missing ferry through lights that remember the dead.',
    'LIGHT',
    'BALANCED',
    [
      d(
        'root',
        1,
        'A Boat Without Oars',
        'An empty ferry knocks against the landing. Across the reeds, lanterns blink the name of its missing keeper. One light waits close enough to touch.',
        [go('Follow the keeper’s lantern', 'light'), go('Search the abandoned ferry', 'boat')],
      ),
      d(
        'light',
        2,
        'Names in the Reeds',
        'A small spirit guards a lantern with no name. It points toward a drowned causeway, then toward a channel marked by cold blue lights.',
        [
          go('Take the old causeway', 'names'),
          check('Ask the spirit to guide you', 'LIGHT', 0.6, 'names', 'current'),
        ],
      ),
      d(
        'boat',
        2,
        'A Hidden Passenger',
        'Under a bench lies the keeper’s ledger. A frightened child says her grandfather followed a voice into the marsh; the ferry rope is already slipping.',
        [go('Take the ledger ashore', 'names'), go('Launch the ferry after him', 'current')],
      ),
      d(
        'names',
        3,
        'The Keeper’s Promise',
        'The ledger names travelers the keeper never brought home. Their lanterns form a path to his island, but each must be acknowledged before you cross.',
        [go('Read each name aloud', 'island'), go('Carry the ledger to the bell tower', 'bell')],
      ),
      d(
        'current',
        3,
        'Water Going Backward',
        'The channel pulls toward the drowned bell tower. The keeper clings to its stairs while pale hands hold his lantern beneath the surface.',
        [
          stat('Pull him onto the landing', 'defense', 140, 'island', 'bell'),
          go('Secure the boat at the bell tower', 'bell'),
        ],
      ),
      d(
        'island',
        4,
        'A Place at the Landing',
        'The keeper will return only if the forgotten passengers have a light at home. He offers his silver lantern to pay for the memorial.',
        [
          go('Build a shared memorial light', 'home'),
          go('Accept the silver lantern as payment', 'silver'),
        ],
      ),
      d(
        'bell',
        4,
        'One Clear Note',
        'The bell can guide the keeper home, but its rope runs through the drowned stairs. Your companion watches the water gather around the tower.',
        [
          check('Ring the bell through the mist', 'LIGHT', 0.6, 'home', 'lost'),
          go('Lead the child back with the ledger', 'silver'),
        ],
      ),
      e(
        'home',
        'The Returning Ferry',
        'At dawn the keeper rows beneath a row of newly named lanterns. No light follows the ferry into the reeds; the village pays you from its rescue fund.',
        'SUCCESS',
        reward(260, 130),
      ),
      e(
        'silver',
        'Something Brought Home',
        'You return with a keepsake and the names the marsh tried to hide. The child lights a candle on the landing and waits beside it.',
        'MIXED',
        reward(170, 80, 15),
      ),
      e(
        'lost',
        'The Bell Below',
        'The rope breaks into the water. You reach shore with your companion, carrying the last echo of a bell that no longer has a tower.',
        'FAILURE',
        { rewards: { xp: 60 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-glass-desert',
    'The Glass Desert',
    'Recover a caravan’s water before the dunes turn sunlight against it.',
    'EARTH',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'A Thousand Horizons',
        'The dunes reflect a caravan that is no longer there. Its real wagons lie buried to their axles, and the water master has followed a false oasis.',
        [go('Trace the buried aqueduct', 'pipe'), go('Follow the water master’s tracks', 'tracks')],
      ),
      d(
        'pipe',
        2,
        'The Singing Conduit',
        'A glass pipe hums beneath your feet. Its access hatch is sealed with sand, while a crack releases a narrow breath of cool air.',
        [
          check('Shape the sand away from the hatch', 'EARTH', 0.6, 'cistern', 'mirage'),
          go('Crawl through the cool fissure', 'mirage'),
        ],
      ),
      d(
        'tracks',
        2,
        'Two Sets of Footprints',
        'The tracks divide beside a discarded waterskin. One trail enters the reflected oasis; the other circles a stone marker untouched by heat.',
        [go('Circle the stone marker', 'cistern'), go('Step toward the reflected palms', 'mirage')],
      ),
      d(
        'cistern',
        3,
        'The Unbroken Surface',
        'Beneath the dunes waits a full cistern. The water master is trapped on its valve platform, afraid that opening the caravan pipe will collapse the roof.',
        [go('Brace the caravan pipe', 'valve'), go('Prepare a rope rescue first', 'rescue')],
      ),
      d(
        'mirage',
        3,
        'An Oasis with Edges',
        'The palms fracture into glass blades. Through them you see the water master and the real cistern, but every hurried step opens another cut.',
        [
          stat('Carry him through the blades', 'defense', 170, 'rescue', 'valve'),
          go('Follow the slow-moving shade', 'valve'),
        ],
      ),
      d(
        'valve',
        4,
        'Water or Crystal',
        'The main valve can fill the wagons or expose a bed of valuable desert crystal. The roof groans as the first wheel turns.',
        [
          go('Send the water to the caravan', 'water'),
          check('Drain the crystal bed first', 'EARTH', 0.45, 'crystal', 'shattered'),
        ],
      ),
      d(
        'rescue',
        4,
        'A Small Enough Burden',
        'The water master hands you a portable filter. You can lead everyone out with a modest supply or return for the reservoir wheel.',
        [
          go('Leave with the filter and survivors', 'water'),
          check('Return for the crystal-lined wheel', 'EARTH', 0.5, 'crystal', 'shattered'),
        ],
      ),
      e(
        'water',
        'A Real Horizon',
        'The wagons move at sunset with enough water for every traveler. Their reflections finally follow them, and the water master pays your share of the rescue.',
        'SUCCESS',
        reward(280, 120),
      ),
      e(
        'crystal',
        'Sunlight in Your Hands',
        'You emerge with a pouch of clear desert crystal. The caravan must ration its water, but the crystal will fetch enough to buy another crossing.',
        'MIXED',
        reward(390, 70, 25),
      ),
      e(
        'shattered',
        'The Oasis Breaks',
        'The roof becomes a rain of shining fragments. You and your companion escape along the shaded wall as the reservoir disappears under the dunes.',
        'FAILURE',
        { rewards: { xp: 70 }, penalties: { energy: 6, credits: { min: 30, max: 50 } } },
      ),
    ],
  ),
  story(
    'the-wandering-library',
    'The Wandering Library',
    'Convince a walking library to return a village’s stolen ending.',
    'SHADOW',
    'SAFE',
    [
      d(
        'root',
        1,
        'Overdue',
        'A library on wooden legs kneels beside the road. The village’s history has vanished from every memory, and a book inside is loudly insisting that you are its villain.',
        [go('Visit the reference desk', 'desk'), go('Answer the accusing book', 'book')],
      ),
      d(
        'desk',
        2,
        'The Index of Absences',
        'The librarian has filed the village under Unfinished Places. A missing page was borrowed by a child whose name is now a blank space.',
        [
          go('Search the children’s shelves', 'child'),
          pay('Pay the archive fee (40 credits)', 40, 'index'),
        ],
      ),
      d(
        'book',
        2,
        'An Unreliable Narrator',
        'The book says you burned the village tomorrow. Between its accusations, a child’s penciled drawing shows a door behind the dictionary shelves.',
        [
          go('Follow the child’s drawing', 'child'),
          check('Read between the moving lines', 'SHADOW', 0.6, 'index', 'child'),
        ],
      ),
      d(
        'child',
        3,
        'A Reader Who Stayed',
        'The child hid inside a happy chapter after losing her home. The library borrowed the village’s future to keep that chapter open.',
        [
          go('Offer to walk her home', 'door'),
          go('Ask the library for a different ending', 'binding'),
        ],
      ),
      d(
        'index',
        3,
        'The Cost of a Conclusion',
        'The index reveals the bargain: one village forgotten, one child safe forever. There is room in the margin for a new promise.',
        [go('Write a promise to the child', 'door'), go('Unpick the original bargain', 'binding')],
      ),
      d(
        'door',
        4,
        'The Last Page',
        'The village appears beyond a paper door. The child asks whether a real home can promise never to hurt; the page waits for an honest answer.',
        [
          go('Promise company, not perfection', 'returned'),
          go('Let her keep a doorway back', 'doorway'),
        ],
      ),
      d(
        'binding',
        4,
        'The Spine Gives Way',
        'The library offers a blank page to replace the stolen future. Writing over it could free the village, but one careless word would close the book on everyone.',
        [
          check('Rewrite the bargain in shadow ink', 'SHADOW', 0.65, 'returned', 'unfinished'),
          go('Keep the archive open to the village', 'doorway'),
        ],
      ),
      e(
        'returned',
        'A Story Still Being Written',
        'The child steps onto an ordinary road. Villagers remember her name before they remember the missing days, and the library leaves a thank-you note in your pocket.',
        'SUCCESS',
        reward(180, 150, 20),
      ),
      e(
        'doorway',
        'Visiting Hours',
        'A small paper door remains in the village school. The library returns each spring, and the child discovers that a favorite chapter can be visited without becoming a home.',
        'SUCCESS',
        reward(140, 130),
      ),
      e(
        'unfinished',
        'A Bookmark, for Now',
        'The ink runs into the binding. You secure a bookmark before the shelves fold shut; the village remembers enough to keep searching, and you carry its first recovered sentence.',
        'MIXED',
        reward(70, 100),
      ),
    ],
  ),
  story(
    'the-ember-forge',
    'The Ember Forge',
    'Repair a forge whose fire has begun forging its own chains.',
    'FIRE',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'Anvil at the Heart',
        'Molten chains crawl out of the royal forge. Its master smith is locked inside, while the fire beneath the anvil speaks in the voice of an unpaid worker.',
        [
          go('Enter through the cooling channel', 'channel'),
          go('Speak into the furnace mouth', 'flame'),
        ],
      ),
      d(
        'channel',
        2,
        'A River of Steam',
        'The cooling gate has jammed. Beyond it, the smith hammers at a chain wrapped around the anvil rather than around him.',
        [
          stat('Lift the cooling gate', 'attack', 160, 'smith', 'debt'),
          go('Reach the forge ledger through a vent', 'debt'),
        ],
      ),
      d(
        'flame',
        2,
        'Wages in Cinders',
        'The furnace spirit has kept the forge alive for a century. It wants the iron token binding it to the crown, hidden beneath the master’s workbench.',
        [
          go('Search beneath the workbench', 'debt'),
          check('Walk through the spirit’s fire', 'FIRE', 0.6, 'smith', 'debt'),
        ],
      ),
      d(
        'smith',
        3,
        'The Master’s Apprentice',
        'The smith is trying to free the spirit. A royal sword anchors the chain; melting it would also destroy the order that pays his apprentices.',
        [
          go('Help melt the royal sword', 'freedom'),
          go('Cool the chain for a careful repair', 'repair'),
        ],
      ),
      d(
        'debt',
        3,
        'The Iron Token',
        'The ledger hides a token stamped with the spirit’s first name. Removing it will silence the furnace unless someone builds a new hearth around ordinary coals.',
        [go('Build the coal hearth', 'repair'), go('Carry the token to the furnace', 'freedom')],
      ),
      d(
        'freedom',
        4,
        'A Fire with a Name',
        'The token glows in your hand. The spirit offers one final masterpiece if you release it before the crown’s chains can reform.',
        [
          go('Release the spirit at once', 'released'),
          check('Forge one last weapon first', 'FIRE', 0.45, 'masterpiece', 'burned'),
        ],
      ),
      d(
        'repair',
        4,
        'The Humble Hearth',
        'Ordinary coals catch beneath the new anvil. The smith can sell his ceremonial tools to pay the apprentices, or risk drawing one final ingot from the old furnace.',
        [
          go('Help sell the ceremonial tools', 'released'),
          check('Draw the final ingot', 'FIRE', 0.55, 'masterpiece', 'burned'),
        ],
      ),
      e(
        'released',
        'Work Worth Doing',
        'For the first time, the forge falls quiet at sunset. Its workers divide their first honest payment with you as a small free flame vanishes into the sky.',
        'SUCCESS',
        reward(270, 140),
      ),
      e(
        'masterpiece',
        'The Last Ingot',
        'The anvil sings once and cracks. The smith pays generously for the strange metal you saved; inside it, a spark refuses to go out.',
        'MIXED',
        {
          rewards: { ...reward(360, 80, 40).rewards, card: { chance: 0.1, minRarity: 'RARE' } },
        },
      ),
      e(
        'burned',
        'Cooling Iron',
        'The old furnace bursts its binding. You escape through the cooling channel with the smith, leaving your scorched gear and the crown’s last sword behind.',
        'FAILURE',
        { rewards: { xp: 65 }, penalties: { energy: 6 } },
      ),
    ],
  ),
];
