import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const dawnStories = [
  story(
    'the-basalt-garden',
    'The Basalt Garden',
    'Restore a stone garden without breaking what its statues protect.',
    'EARTH',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Flowers in Black Stone',
        'Orange flowers grow from the hands of basalt statues. The great stone gardener has stopped moving, and the fountain feeding the garden is splitting down the middle.',
        [
          go('Inspect the cracked fountain', 'fountain'),
          go('Read the statues’ offerings', 'statues'),
        ],
      ),
      d(
        'fountain',
        2,
        'Water Beneath the Basalt',
        'A mineral plug blocks the fountain’s source. Removing it will restore the flow, but the pressure could break the gardener’s already damaged hands.',
        [
          check('Ease the plug from the stone', 'EARTH', 0.6, 'flow', 'hands'),
          go('Divert water toward the gardener’s hands', 'hands'),
        ],
      ),
      d(
        'statues',
        2,
        'Names Without Dates',
        'The statues honor people who returned after the old eruption. Their flowers are seeds for rebuilding, and the gardener has held them safe through another approaching tremor.',
        [
          go('Collect fallen seeds from the paths', 'hands'),
          go('Trace the old irrigation channels', 'flow'),
        ],
      ),
      d(
        'flow',
        3,
        'A Garden Ready to Move',
        'Water reaches the seed beds. The gardener wakes long enough to ask whether the garden should remain a memorial or become a nursery for the valley below.',
        [
          go('Prepare seedlings for the valley', 'valley'),
          go('Repair the memorial fountain', 'memorial'),
        ],
      ),
      d(
        'hands',
        3,
        'What Was Being Held',
        'The gardener opens its cracked palms. Inside lie the last seeds of trees lost to the eruption; it can release them only if someone promises to tend them.',
        [
          go('Promise the seeds a place in the valley', 'valley'),
          go('Plant them around the memorial', 'memorial'),
        ],
      ),
      d(
        'valley',
        4,
        'Roots Beyond the Wall',
        'The first seedling takes hold. A merchant offers to buy the rare mineral soil, while the gardener watches the empty valley beyond its gate.',
        [
          go('Share the seedlings with returning families', 'green'),
          go('Sell part of the soil to fund irrigation', 'stone'),
        ],
      ),
      d(
        'memorial',
        4,
        'A Fountain for the Living',
        'The fountain can be restored with ordinary stone or with the rare crystal in the gardener’s chest. Taking the crystal would leave it unable to move.',
        [
          go('Repair the fountain with ordinary stone', 'green'),
          check('Split a safe sliver from the chest crystal', 'EARTH', 0.45, 'stone', 'fracture'),
        ],
      ),
      e(
        'green',
        'A Memorial with Shade',
        'New trees spread below the statues. The returning families reward you from their rebuilding fund, and the gardener begins making a path wide enough for children.',
        'SUCCESS',
        reward(230, 150, 20),
      ),
      e(
        'stone',
        'The Price of Water',
        'The rare mineral pays for a new irrigation line. You leave with your agreed share while the gardener tends the smaller patch of soil that remains.',
        'MIXED',
        reward(340, 90, 30),
      ),
      e(
        'fracture',
        'A Hand Repaired',
        'A crack runs through the crystal. You spend the afternoon helping brace the gardener’s hand, leaving with its thanks and a little harmless stone dust.',
        'FAILURE',
        { rewards: { xp: 80, dust: 25 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-midnight-bakery',
    'The Midnight Bakery',
    'Catch a pastry thief before the bakery accidentally serves stolen dreams.',
    'SHADOW',
    'SAFE',
    [
      d(
        'root',
        1,
        'Flour at Midnight',
        'Flour footprints cross a bakery that opens only after dark. The baker’s dream-filled pastries are vanishing, and the oven clock insists it is still yesterday.',
        [go('Follow the flour footprints', 'prints'), go('Inspect the oven clock', 'clock')],
      ),
      d(
        'prints',
        2,
        'A Hungry Shadow',
        'A small shadow hides under the cooling rack, clutching a pastry it cannot eat. It belongs to a child who has forgotten how to sleep.',
        [
          go('Ask what dream the child needs', 'dream'),
          go('Bring the shadow to the baker', 'recipe'),
        ],
      ),
      d(
        'clock',
        2,
        'Yesterday’s Batch',
        'The clock has been rebaking the same dream every night. A bent silver hand points toward a recipe labeled Home, while the baker offers a replacement spring.',
        [
          pay('Repair the dream clock (30 credits)', 30, 'dream'),
          check('Follow the dream trapped in the clock', 'SHADOW', 0.65, 'dream', 'recipe'),
          go('Stop the clock and read the old recipe', 'recipe'),
        ],
      ),
      d(
        'dream',
        3,
        'A Door Remembered',
        'The child dreams of a home that no longer exists. The shadow has been stealing pastries to rebuild it crumb by crumb, afraid a new dream would erase the old one.',
        [
          go('Bake room for a new memory', 'new'),
          go('Preserve one pastry from the old dream', 'old'),
        ],
      ),
      d(
        'recipe',
        3,
        'More Than Sugar',
        'The baker admits that the Home recipe uses customers’ happiest memories. He can change the recipe tonight or sell the final enchanted batch to clear his debts.',
        [go('Help rewrite the recipe', 'new'), go('Set aside the final enchanted batch', 'old')],
      ),
      d(
        'new',
        4,
        'The First Unfamiliar Dream',
        'A fresh tray rises in the oven. The shadow asks for a dream with an open door, while the baker wonders whether ordinary pastries will ever draw a queue.',
        [
          go('Give the child the first new pastry', 'sleep'),
          go('Share the tray with the whole street', 'morning'),
        ],
      ),
      d(
        'old',
        4,
        'A Batch Worth a Fortune',
        'Collectors gather at the window. One pastry still holds the child’s old front door; selling it would clear the baker’s debt but leave the shadow outside.',
        [
          go('Keep the child’s pastry and sell the rest', 'morning'),
          check('Free the memory before the auction', 'SHADOW', 0.6, 'sleep', 'crumbs'),
        ],
      ),
      e(
        'sleep',
        'A Light Behind the Door',
        'The child falls asleep before the pastry is finished. The shadow curls beside the bed, and the baker pays you with the first honest profits of a new recipe.',
        'SUCCESS',
        reward(170, 150),
      ),
      e(
        'morning',
        'Open After Dawn',
        'The bakery opens in daylight for the first time. Customers come for the bread as well as the stories, and the baker shares the proceeds of a very unusual night.',
        'SUCCESS',
        reward(250, 100, 15),
      ),
      e(
        'crumbs',
        'A Dream in Pieces',
        'The memory dissolves into crumbs. You help the child gather them into a new picture while the baker abandons the auction and pays for your long night’s work.',
        'MIXED',
        reward(70, 100),
      ),
    ],
  ),
  story(
    'the-thunderstep-arena',
    'The Thunderstep Arena',
    'Enter a storm trial where listening matters as much as strength.',
    'LIGHTNING',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'The Floor Answers',
        'Copper tiles light beneath the arena drums. Its champion offers a trial of three thundersteps, but the young drummer keeps playing a warning between the beats.',
        [
          go('Listen to the drummer before entering', 'rhythm'),
          go('Meet the champion on the copper floor', 'champion'),
        ],
      ),
      d(
        'rhythm',
        2,
        'The Quiet Beat',
        'Three loud beats charge the tiles; the fourth, quiet beat drains them. The drummer points to cracked grounding rods behind the judges’ seats.',
        [
          go('Cross on the quiet fourth beat', 'rods'),
          go('Warn the champion about the grounding rods', 'duel'),
        ],
      ),
      d(
        'champion',
        2,
        'A Champion’s Limp',
        'The champion hides a burned leg. Winning one more trial would pay for new grounding rods, but the judges insist the cracked ones are part of the spectacle.',
        [
          stat('Match the champion’s quick footwork', 'speed', 150, 'rods', 'duel'),
          go('Ask for a cooperative demonstration', 'duel'),
        ],
      ),
      d(
        'rods',
        3,
        'The Storm Below the Seats',
        'The rods channel excess lightning under the spectators. You can stop the trial to repair them or divert the next strike through the empty victory platform.',
        [
          go('Stop the drums for repairs', 'repair'),
          go('Prepare the empty victory platform', 'final'),
        ],
      ),
      d(
        'duel',
        3,
        'Partners on the Floor',
        'The champion agrees to help if the crowd sees a proper contest. A defensive rhythm will buy repair time; a daring final leap could win the purse immediately.',
        [
          go('Use the quiet beat to buy time', 'repair'),
          go('Set up the final leap together', 'final'),
        ],
      ),
      d(
        'repair',
        4,
        'The Fourth Beat',
        'The replacement rod is ready. The drummer waits for your signal while the judges demand one last bright strike for the crowd.',
        [
          go('Ground the rod on the quiet beat', 'safe'),
          check(
            'Ground a full strike for the spectators',
            'LIGHTNING',
            0.55,
            'champion_end',
            'burn',
          ),
        ],
      ),
      d(
        'final',
        4,
        'Above the Copper',
        'The victory platform glows beyond the last charged tile. The champion offers you the safe fourth-beat route, though the judges will pay more for a leap through the lightning.',
        [
          go('Cross together on the quiet beat', 'safe'),
          check('Leap through the final strike', 'LIGHTNING', 0.5, 'champion_end', 'burn'),
        ],
      ),
      e(
        'safe',
        'A Better Trial',
        'The crowd cheers two competitors leaving the floor together. The champion pays your share of the repair purse, and the drummer writes a new rhythm for tomorrow’s trial.',
        'SUCCESS',
        reward(260, 160),
      ),
      e(
        'champion_end',
        'Thunder at Your Heels',
        'You land as the final strike breaks harmlessly above the repaired rod. The judges award the purse, and the champion salutes a victory that leaves the arena safer.',
        'CRITICAL_SUCCESS',
        {
          rewards: {
            credits: { min: 420, max: 420 },
            xp: 110,
            dust: 30,
            card: { chance: 0.1, minRarity: 'RARE' },
          },
        },
      ),
      e(
        'burn',
        'A Beat Too Soon',
        'The tile flashes beneath your landing. The champion pulls you clear and the drummer stops the trial; you leave with a lesson, a scorched boot, and the crowd’s worried applause.',
        'FAILURE',
        { rewards: { xp: 85 }, penalties: { energy: 7 } },
      ),
    ],
  ),
  story(
    'the-last-snowglobe',
    'The Last Snowglobe',
    'Enter a miniature winter before its cracked sky falls apart.',
    'ICE',
    'BALANCED',
    [
      d(
        'root',
        1,
        'A Crack Across the Sky',
        'A wizard’s last snowglobe shakes without a hand touching it. Inside, a tiny village rings its alarm bell; a doorway in the glass grows just large enough for you and your companion.',
        [
          go('Visit the miniature clocktower', 'tower'),
          go('Follow the crack through the village', 'crack'),
        ],
      ),
      d(
        'tower',
        2,
        'A Winter Kept Wound',
        'The clockmaker winds the same winter every morning. The wizard who made the globe never returned, and the clock’s spring is almost worn through.',
        [
          go('Read the wizard’s repair instructions', 'instructions'),
          go('Ask the villagers about leaving', 'choice'),
        ],
      ),
      d(
        'crack',
        2,
        'Beyond the Curved Horizon',
        'Through the crack, the villagers can see a world impossibly large. Some want the sky repaired; others have begun building a staircase from fallen snow crystals.',
        [
          check('Stabilize the crack with clear ice', 'ICE', 0.65, 'instructions', 'choice'),
          go('Help finish the crystal staircase', 'choice'),
        ],
      ),
      d(
        'instructions',
        3,
        'The Maker’s Last Gift',
        'The instructions offer two repairs: a new spring for another century of winter, or a release that lets the village grow to the size of the world outside.',
        [go('Prepare the release mechanism', 'release'), go('Fit a new winter spring', 'winter')],
      ),
      d(
        'choice',
        3,
        'A Village Decides',
        'The villagers ask for one meeting before their sky fails. The clockmaker wants to keep their home, while the children ask what a real summer feels like.',
        [
          go('Let everyone vote on opening the globe', 'release'),
          go('Offer to preserve the village through winter', 'winter'),
        ],
      ),
      d(
        'release',
        4,
        'The Door Becomes a Gate',
        'The release mechanism begins to turn. You can open the globe slowly with every villager ready, or save its valuable crystal shell by drawing the doorway through one narrow crack.',
        [
          go('Open the globe gently for everyone', 'outside'),
          check('Preserve the shell around the doorway', 'ICE', 0.5, 'kept', 'snowfall'),
        ],
      ),
      d(
        'winter',
        4,
        'One More Season',
        'The new spring holds, but the doorway must remain as the village’s choice. The clockmaker offers you the spare crystal if you leave that promise in place.',
        [
          go('Keep the doorway and accept the crystal', 'kept'),
          go('Invite the village to try one day outside', 'outside'),
        ],
      ),
      e(
        'outside',
        'A Summer to Discover',
        'The village unfolds onto the wizard’s abandoned grounds. Its people thank you with the maker’s saved coins before stepping into grass taller than any memory of snow.',
        'SUCCESS',
        reward(250, 150, 20),
      ),
      e(
        'kept',
        'Winter with a Door',
        'The globe settles into quiet snow around an open gate. You leave with a spare crystal and the knowledge that its winter can now be visited instead of endured.',
        'SUCCESS',
        reward(290, 110, 35),
      ),
      e(
        'snowfall',
        'When the Sky Breaks',
        'The shell cracks into a harmless blizzard, scattering the village across the wizard’s table. You help everyone regroup beneath a lamp while the clockmaker begins sketching a sturdier home.',
        'MIXED',
        { rewards: { xp: 100, dust: 30 }, penalties: { energy: 3 } },
      ),
    ],
  ),
  story(
    'the-dawn-archive',
    'The Dawn Archive',
    'Release a stolen sunrise before the coast forgets what morning is.',
    'LIGHT',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Morning on a Shelf',
        'The coast has waited three nights for dawn. In a cliffside archive, bottled sunrises glow behind locked glass while the archivist insists that every morning has an owner.',
        [
          go('Inspect the sunrise catalog', 'catalog'),
          go('Ask the archivist about the dark coast', 'keeper'),
        ],
      ),
      d(
        'catalog',
        2,
        'A Missing Return Date',
        'The current sunrise was borrowed for a royal portrait. Its return date has been scraped away, but a trail of golden condensation leads toward the restoration room.',
        [
          go('Follow the golden condensation', 'bottle'),
          check('Read the erased date in reflected light', 'LIGHT', 0.65, 'debt', 'bottle'),
        ],
      ),
      d(
        'keeper',
        2,
        'The Keeper’s Long Night',
        'The archivist was ordered never to open a bottle without a receipt. The order outlived the king who signed it; the keeper has not stepped outside to notice.',
        [
          go('Show the keeper the waiting coastline', 'debt'),
          go('Request the overdue royal bottle', 'bottle'),
        ],
      ),
      d(
        'bottle',
        3,
        'A Dawn Growing Dim',
        'The stolen sunrise has nearly exhausted itself lighting an unfinished portrait. A fresh bottle could restore it, but that would borrow tomorrow’s morning too.',
        [
          go('Prepare to release the weakened dawn', 'release'),
          go('Restore the bottle with stored archive light', 'restore'),
        ],
      ),
      d(
        'debt',
        3,
        'What Nobody Can Own',
        'The keeper sees fishing boats waiting in darkness. He can annul the royal claim, or sell the unused portrait to fund a careful restoration of the trapped sunrise.',
        [
          go('Annul the claim and open the sea window', 'release'),
          go('Use the portrait’s value for restoration', 'restore'),
        ],
      ),
      d(
        'release',
        4,
        'The First Pale Line',
        'The sea window opens. The dawn will be pale but honest if released now; a final ray caught in a crystal could pay for the archive’s repair.',
        [
          go('Release every remaining ray', 'morning'),
          check('Save one ray without delaying dawn', 'LIGHT', 0.5, 'ray', 'dim'),
        ],
      ),
      d(
        'restore',
        4,
        'Light Owed to Nobody',
        'The restored bottle fills the room with amber. The keeper offers you payment from the portrait sale, then asks who should hold the key to the archive.',
        [
          go('Give the coastal towns a shared key', 'morning'),
          go('Keep the keeper and require public opening hours', 'ray'),
        ],
      ),
      e(
        'morning',
        'The Coast Wakes',
        'A pale sunrise spreads across the fishing boats. The towns reward you together, and the archive’s first public visitor arrives carrying an empty bottle and no claim of ownership.',
        'SUCCESS',
        reward(260, 160, 15),
      ),
      e(
        'ray',
        'A Ray for Tomorrow',
        'Morning returns while the archive begins its repairs. You receive a share of the recovered value, bright enough to remember the coast’s first ordinary day.',
        'SUCCESS',
        {
          rewards: {
            credits: { min: 320, max: 320 },
            xp: 110,
            dust: 30,
            card: { chance: 0.1, minRarity: 'RARE' },
          },
        },
      ),
      e(
        'dim',
        'A Little More Night',
        'The crystal draws too much light. You break it open with the keeper before the bottle fades, sending a delayed dawn over the coast and leaving your hands trembling with its heat.',
        'MIXED',
        { rewards: { xp: 100, dust: 20 }, penalties: { energy: 3 } },
      ),
    ],
  ),
];
