import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const crossingStories = [
  story(
    'the-paper-palace',
    'The Paper Palace',
    'Save a folded kingdom from rain and an impossible royal order.',
    'WATER',
    'BALANCED',
    [
      d(
        'root',
        1,
        'The First Raindrop',
        'Rain darkens the paper palace’s tallest tower. Its folded guards insist the king has forbidden umbrellas, because nothing can be allowed to stand above his crown.',
        [
          go('Enter through the origami garden', 'garden'),
          go('Petition the king at the gate', 'court'),
        ],
      ),
      d(
        'garden',
        2,
        'Cranes with Wet Wings',
        'Paper cranes carry dry leaves toward the nursery. Their gardener has hidden a waterproofing recipe beneath a bridge over the ink river.',
        [
          go('Recover the recipe beneath the bridge', 'recipe'),
          check('Turn the rain away from the cranes', 'WATER', 0.6, 'shelter', 'recipe'),
        ],
      ),
      d(
        'court',
        2,
        'A Crown Too Tall',
        'The king sits beneath a leaking roof, pretending not to notice. His tailor says a lower crown could fit beneath the gardener’s enormous leaf.',
        [
          go('Ask the tailor for a smaller crown', 'shelter'),
          go('Offer to waterproof the royal robes', 'recipe'),
        ],
      ),
      d(
        'recipe',
        3,
        'Ink That Holds',
        'The recipe needs the royal seal melted into wax. It could protect the nursery first or preserve the treasury long enough to pay for rebuilding.',
        [
          go('Carry the wax to the nursery', 'children'),
          go('Offer the wax to the treasurer', 'treasury'),
        ],
      ),
      d(
        'shelter',
        3,
        'A Leaf Above the Crown',
        'The gardener can shelter the nursery beneath one leaf. The king asks whether lowering his crown would make him any less king.',
        [
          go('Invite him to shelter the children', 'children'),
          go('Suggest sheltering the kingdom’s savings', 'treasury'),
        ],
      ),
      d(
        'children',
        4,
        'The Smallest Roof',
        'The king kneels beside the nursery. There is enough wax for its doors or for paper boats that could carry everyone beyond the palace walls.',
        [
          go('Seal the nursery and wait out the rain', 'sheltered'),
          go('Fold boats for a new home', 'boats'),
        ],
      ),
      d(
        'treasury',
        4,
        'A Vault in the Rain',
        'Ink runs down the vault stairs. Saving the ledgers will pay the builders; saving the gold leaves no record of who it belongs to.',
        [
          go('Save the builders’ ledgers', 'sheltered'),
          check('Float the gold out on paper barges', 'WATER', 0.45, 'boats', 'blurred'),
        ],
      ),
      e(
        'sheltered',
        'A Lower Crown',
        'The rain ends over a palace patched with leaves. The king abolishes the umbrella law, and the builders pay you from the ledgers you helped preserve.',
        'SUCCESS',
        reward(230, 130, 15),
      ),
      e(
        'boats',
        'A Kingdom Afloat',
        'Paper boats gather in the quiet river. The court begins rebuilding on higher ground, and your share of the recovered treasury arrives in a neatly folded envelope.',
        'MIXED',
        reward(310, 90),
      ),
      e(
        'blurred',
        'A Wash of Ink',
        'The barges unfold in the current. You rescue their crews and reach the nursery soaked in royal ink; the kingdom will rebuild with fewer coins and better roofs.',
        'FAILURE',
        { rewards: { xp: 80 }, penalties: { energy: 3 } },
      ),
    ],
  ),
  story(
    'the-dragon-kitchen',
    'The Dragon Kitchen',
    'Prepare a peace feast for a dragon who has lost her flame.',
    'FIRE',
    'SAFE',
    [
      d(
        'root',
        1,
        'Dinner for a Dragon',
        'A dragon’s enormous kitchen is cold. Tonight’s peace feast must begin before the mountain clans arrive, but the dragon can produce only embarrassed puffs of smoke.',
        [go('Examine the cold oven', 'oven'), go('Ask what happened to her flame', 'dragon')],
      ),
      d(
        'oven',
        2,
        'A Stubborn Hearth',
        'The oven’s fire sprite refuses to work without a meal of its own. It points to a jar of sun-pepper and a tray of ordinary sweet buns.',
        [
          go('Offer the sprite a sweet bun', 'gentle'),
          check('Toast the sun-pepper with a spark', 'FIRE', 0.65, 'spice', 'gentle'),
        ],
      ),
      d(
        'dragon',
        2,
        'A Burned Tongue',
        'The dragon tasted her own ceremonial pepper and burned her tongue. The cook can make a cooling broth or disguise the missing flame with a spectacular spicy dish.',
        [go('Help prepare the cooling broth', 'gentle'), go('Search the spice cellar', 'spice')],
      ),
      d(
        'gentle',
        3,
        'A Feast That Heals',
        'The dragon’s voice returns over a warm bowl. There is time to serve a simple shared supper or turn the broth into a formal dish worthy of the clans.',
        [
          go('Set one long shared table', 'table'),
          go('Prepare the ceremonial serving bowls', 'ceremony'),
        ],
      ),
      d(
        'spice',
        3,
        'The Last Sun-Pepper',
        'The pepper glows like a coal. A pinch will warm every plate; using the whole fruit could create a flame tall enough to impress the rival chiefs.',
        [
          go('Use a pinch for every guest', 'table'),
          go('Prepare a single grand flambé', 'ceremony'),
        ],
      ),
      d(
        'table',
        4,
        'Who Is Served First',
        'The clans arrive carrying old grudges. The dragon can serve their chiefs by rank, or ask every guest to pass a bowl to someone from the other side.',
        [
          go('Ask the rivals to serve each other', 'peace'),
          go('Honor the chiefs with the first bowls', 'feast'),
        ],
      ),
      d(
        'ceremony',
        4,
        'Fire Above the Table',
        'The serving dish waits beneath the dragon’s restored breath. The cook keeps a safe tray of buns nearby in case ceremony proves hungrier than friendship.',
        [
          check('Raise a controlled spiral of flame', 'FIRE', 0.65, 'feast', 'smoke'),
          go('Serve the buns and speak plainly', 'peace'),
        ],
      ),
      e(
        'peace',
        'A Second Helping',
        'The chiefs argue over recipes instead of borders. The dragon shares the feast fund with you and packs a healing tonic for the road.',
        'SUCCESS',
        {
          rewards: {
            credits: { min: 180, max: 180 },
            xp: 140,
            items: [{ code: 'POTION_MINOR_HP', quantity: 1, chance: 1 }],
          },
        },
      ),
      e(
        'feast',
        'A Proper Celebration',
        'The hall erupts in applause. The clans sign their agreement beneath a curl of harmless smoke, and the dragon rewards you for rescuing her reputation as well as dinner.',
        'SUCCESS',
        reward(260, 100, 15),
      ),
      e(
        'smoke',
        'Supper Outdoors',
        'Smoke sends the guests into the courtyard. The dragon carries out the buns herself; the treaty is delayed, but nobody leaves hungry and the cook still pays for your help.',
        'MIXED',
        reward(90, 80),
      ),
    ],
  ),
  story(
    'the-drowned-bell',
    'The Drowned Bell',
    'Find the right voice to ring a flooded village back to shore.',
    'WATER',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'A Village Under the Hour',
        'Each toll of the drowned bell raises the flood another step. The last residents wait on rooftops while a bell ringer’s ghost insists that morning has not arrived.',
        [go('Row toward the bell tower', 'tower'), go('Visit the rooftop survivors', 'roofs')],
      ),
      d(
        'tower',
        2,
        'The Missing Clapper',
        'The bell sounds without its clapper. A current carries the missing bronze piece around the tower, and the ghost will not let anyone climb past his station.',
        [
          check('Lift the clapper from the current', 'WATER', 0.55, 'bronze', 'song'),
          go('Ask the ghost why he keeps ringing', 'song'),
        ],
      ),
      d(
        'roofs',
        2,
        'The Morning Song',
        'The oldest resident remembers a song that once followed the dawn bell. Her grandson has found a bronze weight in the flood but is afraid to carry it through the tower.',
        [
          go('Learn the village’s morning song', 'song'),
          go('Take the bronze weight to the tower', 'bronze'),
        ],
      ),
      d(
        'song',
        3,
        'A Morning Never Heard',
        'The ghost died before the villagers could answer his final toll. He has mistaken their silence for a night that will never end.',
        [
          go('Gather the survivors into a chorus', 'chorus'),
          go('Bring the ghost to a rooftop at sunrise', 'sunrise'),
        ],
      ),
      d(
        'bronze',
        3,
        'A Heavy Answer',
        'The clapper bears the names of every family in the village. Returning it will let the bell ring once clearly, but someone must hold the cracked beam above it.',
        [
          stat('Brace the beam for the villagers', 'defense', 170, 'chorus', 'sunrise'),
          go('Wait for sunrise before lifting it', 'sunrise'),
        ],
      ),
      d(
        'chorus',
        4,
        'One Answer, Together',
        'The rooftops fill with voices. The ghost raises the rope one last time; you can lead the song or strike the bronze yourself to close the hour.',
        [
          go('Let the village answer its bell', 'recede'),
          check('Strike the bell in harmony with the river', 'WATER', 0.5, 'relic', 'surge'),
        ],
      ),
      d(
        'sunrise',
        4,
        'Light on the Water',
        'Dawn reaches the tower stairs. The ghost sees the living village for the first time and offers his silver bell key in return for an escort out of the tower.',
        [
          go('Escort him into the morning light', 'recede'),
          go('Take the key and ring the silent bell', 'relic'),
        ],
      ),
      e(
        'recede',
        'Streets Beneath the Water',
        'The flood sinks with the last note. Families discover their front steps again, and the village rescue chest finally reaches the people who earned it.',
        'SUCCESS',
        reward(290, 150),
      ),
      e(
        'relic',
        'The Quiet Bell',
        'The tower falls silent and the water steadies. You help the villagers ferry their belongings to higher ground, carrying a share of the rescued silver.',
        'MIXED',
        reward(360, 90, 20),
      ),
      e(
        'surge',
        'An Echo Too Deep',
        'The cracked beam breaks the note in two. You scramble onto the rescue boat as the river takes the empty tower; the survivors begin their song again from shore.',
        'FAILURE',
        { rewards: { xp: 90 }, penalties: { energy: 6 } },
      ),
    ],
  ),
  story(
    'the-mirror-lake',
    'The Mirror Lake',
    'Cross a reflection that offers to undo someone else’s winter.',
    'ICE',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Summer Below Winter',
        'Snow covers the shore, but the lake reflects green trees and a child waving from the far bank. Beside you, an old ferryman refuses to look down.',
        [go('Speak to the ferryman', 'ferry'), go('Answer the reflected child', 'child')],
      ),
      d(
        'ferry',
        2,
        'A Boat for Two Seasons',
        'The ferryman lost his daughter during a winter crossing. He has rowed the same route ever since, hoping the lake will lend him the summer it remembers.',
        [
          go('Inspect his old crossing map', 'map'),
          pay('Hire the boat (40 credits)', 40, 'crossing'),
        ],
      ),
      d(
        'child',
        2,
        'A Voice Through Glass',
        'The reflection says she is a memory, not a prisoner. The lake keeps growing colder each time her father asks her to stay.',
        [
          go('Ask how to release the memory', 'map'),
          check('Freeze a path across the surface', 'ICE', 0.6, 'crossing', 'map'),
        ],
      ),
      d(
        'map',
        3,
        'The Shore That Moved',
        'The map marks a causeway buried beneath the water. On its far end stands the daughter’s memorial, hidden from the ferryman by his own reflection.',
        [
          go('Lead him toward the memorial', 'memorial'),
          go('Carry the memory to the boat', 'bottle'),
        ],
      ),
      d(
        'crossing',
        3,
        'Between the Seasons',
        'The boat glides between falling snow and summer leaves. A silver bottle drifts beside it, able to hold one image before the lake becomes ordinary water.',
        [
          go('Row past the bottle to the memorial', 'memorial'),
          go('Lift the bottle from the water', 'bottle'),
        ],
      ),
      d(
        'memorial',
        4,
        'A Name on Stone',
        'The ferryman finally sees his daughter’s name. She asks him to remember more than the day he lost her, while the lake waits for his next wish.',
        [
          go('Help him speak a happy memory', 'spring'),
          go('Let him keep one summer reflection', 'keepsake'),
        ],
      ),
      d(
        'bottle',
        4,
        'What Can Be Kept',
        'The bottle fills with a bright summer afternoon. Taking more might preserve the whole season, but frost already climbs its neck.',
        [
          go('Keep only the afternoon', 'keepsake'),
          check('Free the whole summer from the glass', 'ICE', 0.5, 'spring', 'cracked'),
        ],
      ),
      e(
        'spring',
        'Water in Its Own Time',
        'The reflection matches the shore. The ferryman gives you the money he saved for impossible crossings, then begins repairing a boat meant for living passengers.',
        'SUCCESS',
        reward(240, 150),
      ),
      e(
        'keepsake',
        'A Small Summer',
        'The ferryman keeps a silver bottle on his windowsill. Winter remains outside, but he thanks you for bringing home a memory that no longer asks him to follow it.',
        'MIXED',
        reward(200, 110, 25),
      ),
      e(
        'cracked',
        'The Ice Gives Way',
        'The bottle cracks and the borrowed summer vanishes. Your companion helps you haul the ferryman onto shore, where the memorial waits without a reflection to hide it.',
        'FAILURE',
        { rewards: { xp: 90 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-ash-caravan',
    'The Ash Caravan',
    'Lead a trade caravan through an ash storm with one lantern left.',
    'FIRE',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'Red Weather',
        'Ash swallows the road behind a stranded caravan. Only one ember lantern remains lit; its master wants to save the cargo while the drivers count the missing travelers.',
        [go('Search the rear wagons', 'wagons'), go('Scout the black cliff path', 'cliff')],
      ),
      d(
        'wagons',
        2,
        'Under the Canvas',
        'Two travelers shelter beneath a collapsed wagon. Its cargo is fireproof seed, valuable enough that the master will not abandon it without proof of another route.',
        [
          stat('Raise the wagon frame', 'attack', 160, 'seeds', 'shelter'),
          go('Cut a way through the canvas', 'shelter'),
        ],
      ),
      d(
        'cliff',
        2,
        'A Line of Orange Flowers',
        'Orange flowers mark a warm fissure through the cliffs. A trader offers a marked route through the lava culvert, while the lantern flickers toward the flowers.',
        [
          go('Follow the hardy flowers', 'shelter'),
          pay('Buy the culvert map (70 credits)', 70, 'seeds'),
        ],
      ),
      d(
        'seeds',
        3,
        'A Future in Sacks',
        'The culvert is wide enough for the seed wagons, but its vent needs a flame before the storm arrives. The lantern could light it, leaving the caravan in darkness.',
        [
          go('Use the lantern to open the vent', 'vent'),
          go('Unload the seed into travelers’ packs', 'packs'),
        ],
      ),
      d(
        'shelter',
        3,
        'Room Beneath the Cliff',
        'The fissure can shelter everyone if the largest wagon stays outside. The master offers a reward to anyone who can find space for its seed cargo.',
        [
          go('Pack only seed and drinking water', 'packs'),
          check('Kindle the old cliff vent', 'FIRE', 0.55, 'vent', 'packs'),
        ],
      ),
      d(
        'vent',
        4,
        'A Breath Through Stone',
        'The vent opens into clear air. A final wagon remains in the ash, and the master’s promised purse hangs beneath its axle.',
        [
          go('Lead everyone through while the vent holds', 'crossed'),
          check('Retrieve the last wagon and purse', 'FIRE', 0.45, 'cargo', 'storm'),
        ],
      ),
      d(
        'packs',
        4,
        'What the Road Can Carry',
        'The travelers can carry the seeds or the master’s decorative wares. The storm will erase whichever cargo stays behind.',
        [
          go('Carry the seeds for the next settlement', 'crossed'),
          go('Carry the valuable wares for trade', 'cargo'),
        ],
      ),
      e(
        'crossed',
        'Green After Ash',
        'The caravan reaches a valley ready for planting. The drivers pay you together, and the first opened seed sack smells unexpectedly of rain.',
        'SUCCESS',
        reward(280, 150, 15),
      ),
      e(
        'cargo',
        'Goods at the Gate',
        'The caravan survives with enough valuable cargo to begin again. The master pays his promised reward while the drivers search the market for replacement seed.',
        'MIXED',
        reward(390, 80),
      ),
      e(
        'storm',
        'The Last Lantern',
        'Ash buries the wagon before you reach it. You follow your companion’s silhouette back to the fissure, carrying the ember lantern and little else.',
        'FAILURE',
        { rewards: { xp: 85 }, penalties: { energy: 7, credits: { min: 20, max: 40 } } },
      ),
    ],
  ),
];
