import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const wildStories = [
  story(
    'the-sleeping-colossus',
    'The Sleeping Colossus',
    'Help a village built on a giant survive its first waking breath.',
    'EARTH',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'The Mountain Breathes',
        'Chimneys tilt as the hill beneath a village exhales. Its oldest bridge leads to a door in the sleeping colossus’s chest; villagers are already packing their homes.',
        [go('Help the villagers reach the bridge', 'village'), go('Enter the chest door', 'heart')],
      ),
      d(
        'village',
        2,
        'A House on a Shoulder',
        'An elderly potter refuses to leave her kiln. A stone tremor breaks the bridge rail, while the village bell begins ringing inside the giant’s ear.',
        [
          go('Silence the village bell', 'dream'),
          stat('Carry the kiln to firm ground', 'defense', 150, 'weight', 'dream'),
        ],
      ),
      d(
        'heart',
        2,
        'Roots Around a Gear',
        'Tree roots have grown through the giant’s heart wheel. Each breath pulls them tighter; a small stone caretaker is trying to loosen them with a gardener’s knife.',
        [
          go('Help untangle the living roots', 'dream'),
          check('Move the heart wheel gently', 'EARTH', 0.55, 'weight', 'dream'),
        ],
      ),
      d(
        'dream',
        3,
        'A Dream of Walking',
        'The colossus dreams of returning to the sea. It does not know that the lights on its shoulders are homes, and its caretaker asks what it should be told.',
        [
          go('Tell it about the village', 'promise'),
          go('Map an evacuation route to the valley', 'road'),
        ],
      ),
      d(
        'weight',
        3,
        'A Burden Chosen',
        'The giant feels every house it carries. It can stay while the villagers move, or rise slowly enough for their bridges to become stairways.',
        [
          go('Ask it to wait one more season', 'promise'),
          go('Help plan the first careful step', 'road'),
        ],
      ),
      d(
        'promise',
        4,
        'A Place to Rest',
        'The giant opens one mossy eye. The villagers offer to tend its heart if it stays, but the sea wind reaches even this far inland.',
        [
          go('Make a home by mutual promise', 'home'),
          go('Promise a village farewell at the sea', 'journey'),
        ],
      ),
      d(
        'road',
        4,
        'The First Step',
        'The valley path is ready. One abandoned storehouse still weighs on a broken shoulder plate; salvaging it would pay for the move but delay the signal.',
        [
          go('Signal the giant to rise', 'journey'),
          check('Lift the storehouse free', 'EARTH', 0.5, 'home', 'fall'),
        ],
      ),
      e(
        'home',
        'A Neighbor, Awake',
        'The colossus rests with its eyes open. The village council finally includes the owner of its hill, and you receive a reward from the relocation fund.',
        'SUCCESS',
        reward(280, 140, 20),
      ),
      e(
        'journey',
        'Footprints Toward the Sea',
        'The last family reaches the valley before the giant stands. It waves a hand the size of a field, and the grateful villagers share their saved supplies.',
        'SUCCESS',
        {
          rewards: {
            credits: { min: 230, max: 230 },
            xp: 150,
            items: [{ code: 'POTION_MAJOR_HP', quantity: 1, chance: 1 }],
          },
        },
      ),
      e(
        'fall',
        'A Shoulder of Rubble',
        'The plate gives way under the storehouse. Your companion helps you reach the valley while the giant pauses, patiently, for the dust to settle.',
        'FAILURE',
        { rewards: { xp: 80, dust: 20 }, penalties: { energy: 5 } },
      ),
    ],
  ),
  story(
    'the-mushroom-post',
    'The Mushroom Post',
    'Deliver a letter that keeps changing its address.',
    'EARTH',
    'SAFE',
    [
      d(
        'root',
        1,
        'Return to Someone',
        'The mushroom postmaster hands you a letter whose address grows new roots whenever you look away. It must reach its recipient before the forest’s spring meeting.',
        [go('Ask the sorting beetles', 'beetles'), go('Follow the roots on the envelope', 'roots')],
      ),
      d(
        'beetles',
        2,
        'The Scent of Home',
        'The beetles recognize the sender’s moss perfume. Two routes remain: an old badger tunnel or the bright cap-bridge over the creek.',
        [
          go('Take the badger tunnel', 'burrow'),
          pay('Hire the beetle courier (30 credits)', 30, 'bridge'),
        ],
      ),
      d(
        'roots',
        2,
        'A Moving Address',
        'The envelope points to a stump, then to a sapling farther downstream. Its recipient appears to be a tree that has learned to walk.',
        [
          check('Listen through the forest floor', 'EARTH', 0.7, 'burrow', 'bridge'),
          go('Follow the sapling footprints', 'bridge'),
        ],
      ),
      d(
        'burrow',
        3,
        'The Unsent Reply',
        'In the burrow you find years of letters to a departed willow. A young walking tree has been answering them, afraid to admit that its parent is gone.',
        [
          go('Carry the truth to the sender', 'sender'),
          go('Find the young tree before the meeting', 'sapling'),
        ],
      ),
      d(
        'bridge',
        3,
        'Across the Cap-Bridge',
        'The young tree waits by the creek with ink on its roots. It asks whether a letter can belong to someone who is no longer here.',
        [
          go('Invite it to meet the sender', 'sender'),
          go('Help it write a reply in its own name', 'sapling'),
        ],
      ),
      d(
        'sender',
        4,
        'An Old Friend’s Door',
        'An ancient hedgehog opens the letter with shaking paws. The sapling waits outside, carrying a blossom from the willow’s last spring.',
        [
          go('Introduce the sapling honestly', 'friends'),
          go('Leave the blossom and a gentle goodbye', 'farewell'),
        ],
      ),
      d(
        'sapling',
        4,
        'A Name of Its Own',
        'The sapling’s first signature winds across the page. A sudden breeze threatens to scatter the letter into the creek before the meeting bell rings.',
        [
          go('Deliver the reply by the sheltered path', 'friends'),
          check('Catch the spring wind to arrive first', 'EARTH', 0.6, 'farewell', 'late'),
        ],
      ),
      e(
        'friends',
        'Forwarding Address',
        'The hedgehog and the sapling arrive at the meeting together. The postmaster stamps your receipt with a tiny mushroom and pays you for a delivery nobody else could finish.',
        'SUCCESS',
        reward(150, 130, 10),
      ),
      e(
        'farewell',
        'A Letter Kept',
        'The old hedgehog folds the letter beside a new blossom. The postmaster gives you the delivery fee and a packet of tonic for the walk home.',
        'SUCCESS',
        {
          rewards: {
            credits: { min: 120, max: 120 },
            xp: 100,
            items: [{ code: 'POTION_MINOR_HP', quantity: 1, chance: 1 }],
          },
        },
      ),
      e(
        'late',
        'Tomorrow’s Post',
        'The wind carries the envelope into a puddle. You dry every page by the postmaster’s stove; the meeting will have to wait for tomorrow’s delivery.',
        'MIXED',
        reward(50, 80),
      ),
    ],
  ),
  story(
    'the-silver-mill',
    'The Silver Mill',
    'Discover why a village mill is grinding moonlight instead of grain.',
    'WATER',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Flour That Glows',
        'Silver flour drifts from the mill windows, but the village bread has become too light to hold. The miller points at a waterwheel turning against the river.',
        [go('Inspect the upstream sluice', 'sluice'), go('Examine the millstones', 'stones')],
      ),
      d(
        'sluice',
        2,
        'The River’s Reflection',
        'A silver fish circles the gate, carrying a stolen moon shard in its mouth. Opening the sluice could bring it inside or release it downstream.',
        [
          check('Guide the fish into a calm pool', 'WATER', 0.6, 'fish', 'flood'),
          go('Close the lower gate first', 'flood'),
        ],
      ),
      d(
        'stones',
        2,
        'A Wish in the Grain',
        'The millstones bear a wish for a harvest that never ends. The miller admits casting a silver coin into the river during last winter’s hunger.',
        [
          go('Ask the river to return the coin', 'fish'),
          go('Stop the enchanted millstones', 'flood'),
        ],
      ),
      d(
        'fish',
        3,
        'The Bargain’s Other Half',
        'The river granted endless flour by borrowing the moon’s reflection. The fish can return it, but the miller must give up the wish before the next wheel turn.',
        [
          go('Help the miller release the wish', 'release'),
          go('Measure one final batch of silver flour', 'batch'),
        ],
      ),
      d(
        'flood',
        3,
        'A Wheel with No Rest',
        'Water climbs the mill stairs. A brake could stop the wheel, while opening the granary chute would let the enchanted flour flow back into the river.',
        [
          go('Open the granary chute', 'release'),
          stat('Hold the wheel brake', 'defense', 140, 'batch', 'release'),
        ],
      ),
      d(
        'release',
        4,
        'Ordinary Bread',
        'The silver fish waits beside the coin. The villagers offer their winter seed to restart the mill, or you can take a small share of silver flour as payment.',
        [
          go('Return the coin and replant together', 'bread'),
          go('Keep a measured pouch of silver flour', 'silver'),
        ],
      ),
      d(
        'batch',
        4,
        'The Final Sack',
        'The scale trembles between a useful handful and a fortune. The river rises every time you add another scoop.',
        [
          go('Take only a handful and stop', 'silver'),
          check('Balance one full silver sack', 'WATER', 0.45, 'windfall', 'spill'),
        ],
      ),
      e(
        'bread',
        'Weight Enough to Share',
        'The first ordinary loaf stays on the table. The villagers divide it before dividing your payment, while a whole moon appears in the river outside.',
        'SUCCESS',
        reward(240, 130),
      ),
      e(
        'silver',
        'A Little Moonlight',
        'You leave with a pouch of shining flour and a modest miller’s fee. The wheel turns normally, and every loaf now carries only the smallest silver crust.',
        'MIXED',
        reward(300, 70, 20),
      ),
      e(
        'spill',
        'A River Repaid',
        'The sack bursts into the water. You and the miller scramble upstairs as the river takes back its borrowed light and a few of your loose belongings.',
        'FAILURE',
        { rewards: { xp: 65 }, penalties: { credits: { min: 25, max: 45 }, energy: 3 } },
      ),
      e(
        'windfall',
        'A Measured Fortune',
        'The final sack balances just as the wheel stops. The miller sells enough silver flour to restore the riverbank and pays you a share before returning to ordinary grain.',
        'CRITICAL_SUCCESS',
        reward(400, 100, 30),
      ),
    ],
  ),
  story(
    'the-thorn-castle',
    'The Thorn Castle',
    'Untangle a castle’s curse without mistaking its gardener for its prisoner.',
    'EARTH',
    'BALANCED',
    [
      d(
        'root',
        1,
        'Roses at the Gate',
        'Thorns close around a castle that was empty yesterday. A voice behind the rose-glass gate asks you to leave; a royal messenger asks you to break it open.',
        [
          go('Speak through the garden wall', 'garden'),
          go('Read the messenger’s decree', 'decree'),
        ],
      ),
      d(
        'garden',
        2,
        'A Careful Gardener',
        'The gardener tends flowers around the sleeping court. He says the thorns grew when soldiers tried to take the castle’s last healing rose.',
        [
          go('Inspect the healing beds', 'rose'),
          check('Ask the roots to reveal the past', 'EARTH', 0.6, 'memory', 'rose'),
        ],
      ),
      d(
        'decree',
        2,
        'The Seal Is Fresh',
        'The decree promises the rose to the highest bidder, not to the sick. Its wax seal covers a second order calling the gardener a thief.',
        [
          go('Compare the two orders', 'memory'),
          go('Find the rose before the messenger does', 'rose'),
        ],
      ),
      d(
        'rose',
        3,
        'Enough for a Garden',
        'The last rose holds a cluster of seeds. Picking the bloom would heal one patron today; planting the seeds could heal many people next spring.',
        [go('Prepare the seed bed', 'seeds'), go('Arrange safe passage for the bloom', 'bloom')],
      ),
      d(
        'memory',
        3,
        'Who Cast the Curse',
        'The roots show the court ordering its own sleep until the siege ended. The gardener kept watch alone, and the messenger’s soldiers are returning.',
        [
          go('Wake the court to witness the truth', 'seeds'),
          go('Bargain with the messenger using the rose', 'bloom'),
        ],
      ),
      d(
        'seeds',
        4,
        'The Gate Opens Inward',
        'The court stirs as new roots spread. The gardener offers you a seed, but the gate will only stay open if the thorn crown is buried beneath it.',
        [
          go('Bury the crown and keep the garden open', 'gardened'),
          check('Keep the crown as a living relic', 'EARTH', 0.5, 'relic', 'snared'),
        ],
      ),
      d(
        'bloom',
        4,
        'A Rose in the Road',
        'The messenger reaches for the bloom. A village healer waits behind him, with no money and a patient who cannot wait until spring.',
        [
          go('Give the bloom to the healer', 'gardened'),
          go('Sell the bloom with its seeds intact', 'relic'),
        ],
      ),
      e(
        'gardened',
        'A Public Garden',
        'The thorn walls become hedges beside an open road. The court pays you for ending its long vigil, and the gardener finally leaves his gate to visit the village.',
        'SUCCESS',
        reward(260, 140, 15),
      ),
      e(
        'relic',
        'A Thorn in the Bargain',
        'You depart with payment and a living remnant of the castle. Its roots curl around your reward, as if reminding you that every garden needs a keeper.',
        'MIXED',
        reward(350, 80, 30),
      ),
      e(
        'snared',
        'The Crown Tightens',
        'The thorns refuse to leave their gate. The gardener cuts you free and closes the relic beneath the soil, leaving you with scratches and one ordinary rose.',
        'FAILURE',
        { rewards: { xp: 75 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-starfall-crater',
    'The Starfall Crater',
    'Choose the fate of a fallen star before scavengers dismantle it.',
    'LIGHT',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'A Second Dawn',
        'Blue light rises from a new crater. Scavengers hurry toward its rim, while a voice inside the fallen stone asks whether the sky is still above it.',
        [go('Speak to the fallen star', 'voice'), go('Approach the scavenger camp', 'camp')],
      ),
      d(
        'voice',
        2,
        'A Small Voice in Stone',
        'The star remembers a constellation with one missing place. Its shell is cooling; a lens could show it the way home, while a mining drill would open its heart.',
        [go('Look for a usable lens', 'lens'), go('Inspect the cracked shell', 'shell')],
      ),
      d(
        'camp',
        2,
        'Rights of Salvage',
        'The scavenger chief offers you a share for opening the shell. An apprentice quietly points to a telescope confiscated from the nearby observatory.',
        [
          pay('Buy back the telescope (80 credits)', 80, 'lens'),
          go('Join the shell inspection', 'shell'),
        ],
      ),
      d(
        'lens',
        3,
        'The Missing Place',
        'The telescope finds a dark gap in a bright constellation. The star can rise if its shell is opened carefully, but the chief has already started the drill.',
        [
          go('Redirect the drill into a release channel', 'launch'),
          go('Negotiate a share of the empty shell', 'claim'),
        ],
      ),
      d(
        'shell',
        3,
        'Heat Beneath the Cracks',
        'The shell contains both rare metal and a frightened light. Every strike makes the crater brighter; your companion senses a pulse approaching.',
        [
          check('Calm the star’s pulse', 'LIGHT', 0.6, 'launch', 'claim'),
          go('Move the miners behind the rim', 'claim'),
        ],
      ),
      d(
        'launch',
        4,
        'A Window to the Sky',
        'The release channel opens beneath the constellation. You can launch the star intact or chip a bright fragment away before it leaves.',
        [
          go('Send the whole star home', 'sky'),
          check('Take a fragment without harming it', 'LIGHT', 0.45, 'fragment', 'flare'),
        ],
      ),
      d(
        'claim',
        4,
        'What Salvage Means',
        'The chief will accept the cooling shell if you release the light now. Holding it longer might create a more valuable crystal, but the crater hums with pressure.',
        [
          go('Release the light and split the shell', 'sky'),
          check('Crystallize the remaining light', 'LIGHT', 0.45, 'fragment', 'flare'),
        ],
      ),
      e(
        'sky',
        'A Constellation Mended',
        'The missing place fills with blue light. The scavengers share the harmless metal left behind, and a new star follows you above the road home.',
        'SUCCESS',
        reward(310, 150, 30),
      ),
      e(
        'fragment',
        'A Pocket of Night',
        'A small star fragment cools in your hand. The sky receives the rest, and the observatory buys the strange crystal for its next generation of lenses.',
        'MIXED',
        {
          rewards: {
            credits: { min: 380, max: 380 },
            xp: 90,
            dust: 45,
            card: { chance: 0.1, minRarity: 'RARE' },
          },
        },
      ),
      e(
        'flare',
        'Too Much Dawn',
        'The crater blooms into white light. You reach the rim with the miners, dazzled and empty-handed, as the star tears its own path back into the sky.',
        'FAILURE',
        { rewards: { xp: 90 }, penalties: { energy: 7 } },
      ),
    ],
  ),
];
