import {
  story,
  decision as d,
  ending as e,
  go,
  pay,
  check,
  stat,
  reward,
} from './story-helpers.js';

export const nightfallStories = [
  story(
    'the-moonlit-menagerie',
    'The Moonlit Menagerie',
    'Find out why the moon-beasts have opened their cages.',
    'LIGHT',
    'SAFE',
    [
      d(
        'root',
        1,
        'Every Cage Is Open',
        'Silver feathers cover the menagerie path. The night keeper is missing, and a luminous stag stands patiently outside its unlocked cage.',
        [go('Follow the stag', 'stag'), go('Search the keeper’s lodge', 'lodge')],
      ),
      d(
        'stag',
        2,
        'A Trail of Hoofprints',
        'The stag leads you to a fountain full of moon-moths. Their wings conceal the keeper’s fallen whistle; catching them might scatter the herd.',
        [
          check('Gather the moths in gentle light', 'LIGHT', 0.65, 'whistle', 'herd'),
          go('Follow the herd beyond the fountain', 'herd'),
        ],
      ),
      d(
        'lodge',
        2,
        'The Keeper’s Last Entry',
        'The keeper planned to release the animals before a collector arrived. His whistle is missing, but a map marks a moon gate behind the nursery.',
        [
          go('Take the map to the nursery', 'herd'),
          go('Search the fountain for the whistle', 'whistle'),
        ],
      ),
      d(
        'whistle',
        3,
        'A Familiar Note',
        'The whistle brings the keeper out of hiding. He asks you to guide the beasts through the moon gate before the collector closes the grounds.',
        [
          go('Lead the beasts to the moon gate', 'gate'),
          go('Meet the collector at the front entrance', 'collector'),
        ],
      ),
      d(
        'herd',
        3,
        'The Smallest Beast',
        'A young moon-hare refuses to leave its cage. The keeper waits beside it, unable to abandon the smallest animal while the collector’s lamps approach.',
        [
          go('Carry the hare toward the moon gate', 'gate'),
          go('Ask the collector to spare the nursery', 'collector'),
        ],
      ),
      d(
        'gate',
        4,
        'Room for One More',
        'The moon gate is fading. The keeper can follow his animals, or remain to turn the empty menagerie into a refuge for ordinary wounded creatures.',
        [go('Hold the gate for the keeper', 'wild'), go('Help him build a new refuge', 'refuge')],
      ),
      d(
        'collector',
        4,
        'The Price of Wonder',
        'The collector offers a purse for the whistle. Without it, the animals can never be summoned back; he has not noticed the keeper opening the rear gate.',
        [
          go('Sell the empty promise and let them flee', 'refuge'),
          check('Dazzle the collector’s lamps', 'LIGHT', 0.6, 'wild', 'delayed'),
        ],
      ),
      e(
        'wild',
        'Hooves on Moonlight',
        'The herd climbs a path of silver air. One feather drifts down with the keeper’s farewell, and the unused keeper’s wages become your reward.',
        'SUCCESS',
        reward(200, 130, 20),
      ),
      e(
        'refuge',
        'Open Doors',
        'The moon-beasts vanish into the woods. By morning the first injured fox sleeps in a cage with no door, and the keeper pays you for helping make room.',
        'SUCCESS',
        reward(240, 100),
      ),
      e(
        'delayed',
        'A Longer Way Home',
        'The lamps flare instead of failing. You guide the herd into the forest one animal at a time; the keeper thanks you, though the moon gate closes before he can follow.',
        'MIXED',
        reward(100, 100),
      ),
    ],
  ),
  story(
    'the-storm-train',
    'The Storm Train',
    'Stop a runaway train before its conductor becomes the storm.',
    'LIGHTNING',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'Tickets to Thunder',
        'A train screams across the viaduct with no station ahead. Blue sparks trace a conductor’s outline at the engine window; the passengers are still waiting for their stop.',
        [go('Check the passenger carriage', 'passengers'), go('Climb toward the engine', 'roof')],
      ),
      d(
        'passengers',
        2,
        'The Unpunched Ticket',
        'One passenger holds a ticket dated a hundred years ago. She recognizes the storm-conductor as her brother and asks you to carry him her farewell.',
        [
          go('Carry her message through the carriage', 'message'),
          pay('Buy the engineer’s insulated gloves (50 credits)', 50, 'brake'),
        ],
      ),
      d(
        'roof',
        2,
        'Copper and Rain',
        'The roof conducts every lightning strike toward the engine. A disconnected brake cable swings beside a service window.',
        [
          check('Ride the charge to the brake cable', 'LIGHTNING', 0.55, 'brake', 'message'),
          go('Enter through the service window', 'message'),
        ],
      ),
      d(
        'message',
        3,
        'One Stop Too Late',
        'The conductor repeats the name of a station demolished long ago. His sister’s farewell might let him stop, but the train needs somewhere safe to arrive.',
        [go('Signal the abandoned platform', 'platform'), go('Set the emergency siding', 'siding')],
      ),
      d(
        'brake',
        3,
        'The Last Brake Shoe',
        'The brake can hold for only one turn. Beyond the bridge lies a ruined platform; a gravel siding climbs away from the tracks.',
        [
          go('Brake toward the ruined platform', 'platform'),
          go('Brake toward the uphill siding', 'siding'),
        ],
      ),
      d(
        'platform',
        4,
        'Arrival',
        'The platform appears through the rain. The conductor cannot read its broken sign, and the sister’s voice is almost lost beneath the wheels.',
        [
          check('Light the station name in sparks', 'LIGHTNING', 0.6, 'station', 'wreck'),
          go('Uncouple the carriages beside the platform', 'saved'),
        ],
      ),
      d(
        'siding',
        4,
        'No More Track',
        'Gravel sprays beneath the train. You can uncouple the engine to save the carriages or try to ground the storm through the final rail.',
        [
          go('Uncouple and save the passengers', 'saved'),
          check('Ground the engine’s storm', 'LIGHTNING', 0.45, 'station', 'wreck'),
        ],
      ),
      e(
        'station',
        'The Waiting Ends',
        'The conductor steps onto the platform beside his sister. The train settles into ordinary rain, leaving you an old railway payment chest and a quiet route home.',
        'SUCCESS',
        reward(320, 140, 20),
      ),
      e(
        'saved',
        'A Safe Siding',
        'The carriages stop with every passenger aboard. Far up the mountain the engine thunders on alone; the railway pays you for the lives you brought back.',
        'MIXED',
        reward(240, 110),
      ),
      e(
        'wreck',
        'After the Thunder',
        'The last rail melts. You pull the passengers into the service shelter as the empty engine leaves the viaduct in a shower of blue sparks.',
        'FAILURE',
        { rewards: { xp: 90 }, penalties: { energy: 6 } },
      ),
    ],
  ),
  story(
    'the-coral-court',
    'The Coral Court',
    'Resolve a pearl dispute before an underwater kingdom closes its gates.',
    'WATER',
    'BALANCED',
    [
      d(
        'root',
        1,
        'A Pearl on the Scales',
        'The coral queen’s pearl has stopped the tide. A fisher and a reef guardian each claim it, and the court asks an outsider to hear their stories.',
        [go('Hear the fisher’s testimony', 'fisher'), go('Visit the reef guardian', 'reef')],
      ),
      d(
        'fisher',
        2,
        'The Empty Net',
        'The fisher found the pearl inside a torn net. It pulses whenever he speaks of his hungry village, but fades when he calls it his property.',
        [go('Examine the torn net', 'evidence'), go('Ask what the village truly needs', 'need')],
      ),
      d(
        'reef',
        2,
        'The Reef’s Missing Heart',
        'The guardian says the pearl kept young coral alive. A current carried it away after the court diverted water toward the royal gardens.',
        [
          check('Read the old currents', 'WATER', 0.65, 'evidence', 'need'),
          go('Inspect the starving coral', 'need'),
        ],
      ),
      d(
        'evidence',
        3,
        'The Royal Channel',
        'Shell maps prove the queen’s gardens changed the current. Revealing them will embarrass the crown; trading them privately could fund the village.',
        [
          go('Present the maps to the court', 'hearing'),
          go('Negotiate with the royal steward', 'bargain'),
        ],
      ),
      d(
        'need',
        3,
        'Two Kinds of Hunger',
        'The village needs fish and the reef needs flowing water. Both would recover if the garden channel reopened, though the queen would lose her rare blossoms.',
        [
          go('Propose reopening the channel', 'hearing'),
          go('Ask the steward to buy new fishing boats', 'bargain'),
        ],
      ),
      d(
        'hearing',
        4,
        'The Queen’s Reflection',
        'The queen studies the silent pearl. She will accept a public apology from one claimant, or let you carry the pearl back while she opens the garden gate herself.',
        [
          go('Return the pearl and open the gate together', 'balance'),
          go('Accept the court’s compensation', 'payment'),
        ],
      ),
      d(
        'bargain',
        4,
        'A Quiet Settlement',
        'The steward offers a generous purse for silence. A small side sluice might restore the reef without a hearing, but it lies beneath a crushing current.',
        [
          go('Take compensation for the village', 'payment'),
          check('Open the hidden sluice', 'WATER', 0.5, 'balance', 'swept'),
        ],
      ),
      e(
        'balance',
        'The Tide Returns',
        'Water moves through the reef again. The queen plants ordinary sea grass where her rare flowers stood, and both claimants insist you share their reward.',
        'SUCCESS',
        reward(250, 140, 25),
      ),
      e(
        'payment',
        'A Purse Above Water',
        'New boats reach the village while the pearl remains in court. You leave with payment and a promise that the reef will be discussed at the next tide.',
        'MIXED',
        reward(330, 70),
      ),
      e(
        'swept',
        'Below the Hearing',
        'The current tears the sluice handle free. The guardian brings you safely to shore, carrying the evidence the court can no longer quietly ignore.',
        'FAILURE',
        { rewards: { xp: 80, dust: 15 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-hollow-theater',
    'The Hollow Theater',
    'Help a haunted troupe perform an ending its audience never heard.',
    'SHADOW',
    'BALANCED',
    [
      d(
        'root',
        1,
        'A Seat Reserved',
        'A ticket with your name waits at an abandoned theater. Onstage, a wooden actor repeats the first line of a tragedy while the orchestra tunes without musicians.',
        [go('Step behind the curtain', 'backstage'), go('Sit in the reserved seat', 'audience')],
      ),
      d(
        'backstage',
        2,
        'The Missing Final Act',
        'The stage manager guards a burned script. Its final act was cut by a patron who disliked the heroine surviving; the original pages may still be in the prompt box.',
        [
          go('Search the prompt box', 'script'),
          check('Question the shadows in the wings', 'SHADOW', 0.6, 'truth', 'script'),
        ],
      ),
      d(
        'audience',
        2,
        'The Patron’s Box',
        'A masked spectator applauds every death. An old usher whispers that the patron paid for a tragedy and has refused to let the actors leave.',
        [
          go('Speak with the frightened usher', 'truth'),
          go('Take the script from the empty seat', 'script'),
        ],
      ),
      d(
        'script',
        3,
        'A Different Last Line',
        'The recovered page gives the heroine a boat and a way out. Replacing the stage prop will change the ending; the patron’s mask is already turning toward you.',
        [
          go('Set the boat beside the stage', 'performance'),
          go('Confront the patron in the box', 'mask'),
        ],
      ),
      d(
        'truth',
        3,
        'Who Owns the Curtain',
        'The usher reveals that the patron is only an actor afraid of a world without his role. His mask holds the contract keeping the theater shut.',
        [
          go('Offer him a new role in the ending', 'performance'),
          go('Demand the contract from his mask', 'mask'),
        ],
      ),
      d(
        'performance',
        4,
        'The Curtain Rises',
        'The heroine reaches the river. The audience expects her to fall; your companion holds the boat steady while the patron waits for his cue.',
        [
          go('Give the heroine her new last line', 'ovation'),
          go('Let the patron take the final bow', 'encore'),
        ],
      ),
      d(
        'mask',
        4,
        'A Face Behind the Part',
        'The mask offers you the ticket receipts if you leave the play unchanged. Its paper contract trembles in the light from the stage.',
        [
          go('Accept the receipts and end your visit', 'encore'),
          check('Tear the shadow contract', 'SHADOW', 0.55, 'ovation', 'trapped'),
        ],
      ),
      e(
        'ovation',
        'An Unrehearsed Dawn',
        'The boat reaches the far bank. The actors bow as themselves, and the theater doors open on morning; the troupe shares its long-forgotten receipts with you.',
        'SUCCESS',
        reward(260, 140, 20),
      ),
      e(
        'encore',
        'One More Performance',
        'You leave with a share of the house money. Behind you, the patron asks the orchestra to begin again, though the heroine now watches the river differently.',
        'MIXED',
        reward(340, 60),
      ),
      e(
        'trapped',
        'The Understudy',
        'The contract tears into a new ticket bearing your name. You escape through the orchestra pit before the stage can assign you a role.',
        'FAILURE',
        { rewards: { xp: 70 }, penalties: { energy: 4 } },
      ),
    ],
  ),
  story(
    'the-frostbound-lighthouse',
    'The Frostbound Lighthouse',
    'Relight a beacon while its keeper tries to hold back the thaw.',
    'ICE',
    'HIGH_RISK',
    [
      d(
        'root',
        1,
        'A Light Under Ice',
        'The lighthouse beam points into the frozen sea instead of across it. Ships gather offshore, and something beneath the ice answers every rotation with a knock.',
        [go('Climb to the lantern room', 'lens'), go('Follow the knocks across the ice', 'ice')],
      ),
      d(
        'lens',
        2,
        'The Keeper’s Hand',
        'The keeper grips a frozen lever. He trapped a rescue boat beneath the ice years ago and fears that a working beacon will reveal it.',
        [
          go('Ask for the rescue log', 'log'),
          check('Ease the ice from the lever', 'ICE', 0.6, 'boat', 'log'),
        ],
      ),
      d(
        'ice',
        2,
        'The Shape Below',
        'A rescue boat hangs in clear ice, its passengers untouched by time. A lantern inside still burns, connected to the lighthouse by a thread of blue light.',
        [
          go('Trace the lantern’s thread', 'log'),
          stat('Lower a rope through the ice shaft', 'defense', 160, 'boat', 'log'),
        ],
      ),
      d(
        'log',
        3,
        'An Unfinished Rescue',
        'The log shows the keeper froze the boat to save it from a storm. The spell needs a new harbor light before the passengers can safely wake.',
        [
          go('Prepare the harbor signal', 'signal'),
          go('Carry a spare lantern onto the ice', 'thaw'),
        ],
      ),
      d(
        'boat',
        3,
        'The First Breath',
        'One passenger opens her eyes. The boat will drift as soon as the ice releases it; the lighthouse lens or your rope must guide it to shore.',
        [go('Set the lens toward the harbor', 'signal'), go('Brace the rescue rope', 'thaw')],
      ),
      d(
        'signal',
        4,
        'Where the Beam Belongs',
        'The lens is warm enough to turn. You can guide the trapped boat home or first steer the waiting merchant ships through the outer channel.',
        [
          go('Guide the rescue boat home', 'rescue'),
          go('Open the merchant channel first', 'trade'),
        ],
      ),
      d(
        'thaw',
        4,
        'The Ice Lets Go',
        'The boat begins to move. The rope tightens against a cracked bollard while your companion stands between the keeper and the open water.',
        [
          check('Thaw a safe channel around the boat', 'ICE', 0.55, 'rescue', 'adrift'),
          go('Signal the merchant ships for help', 'trade'),
        ],
      ),
      e(
        'rescue',
        'A Harbor After Winter',
        'The passengers step ashore into a year they never expected to see. The keeper turns the beam toward open water and gives you the lighthouse rescue fund.',
        'SUCCESS',
        reward(300, 150, 20),
      ),
      e(
        'trade',
        'Lights on the Horizon',
        'Merchant crews tow the rescue boat the long way around. Everyone reaches harbor late, and the captains pay you for reopening the frozen channel.',
        'MIXED',
        reward(350, 90),
      ),
      e(
        'adrift',
        'A Light Still Moving',
        'The rope parts. You leave the spare lantern aboard before reaching shore; a patrol ship follows its glow while you and the keeper tend your frozen hands.',
        'FAILURE',
        { rewards: { xp: 80 }, penalties: { energy: 6 } },
      ),
    ],
  ),
];
