import type { NewGameItem, GameItemRepository } from '@ririko/database';

export const CANONICAL_ITEMS: NewGameItem[] = [
  // ─── EQUIPMENTS: WEAPONS ───────────────────────────────────────────────────
  {
    code: 'WEAPON_NOVICE_BLADE',
    name: 'Novice Blade',
    description: 'A standard starter training sword forged for new summoners.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'COMMON',
    baseStats: { attack: 25, critRate: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SCOUT_BOOMERANG',
    name: 'Scout Boomerang',
    description: 'A swift, balanced curved blade that returns to its wielder with agility.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'UNCOMMON',
    baseStats: { attack: 45, speed: 5, critRate: 0.03 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 250,
    maxDailyPurchases: 3,
    isTradeable: true,
  },
  {
    code: 'WEAPON_OBSIDIAN_KATANA',
    name: 'Obsidian Katana',
    description: 'A razor-sharp volcanic blade that punctures hardened defenses with ease.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'RARE',
    baseStats: { attack: 110, critRate: 0.08, critDamage: 0.15 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 1000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SOLAR_LANCE',
    name: 'Solar Lance',
    description: 'A radiant spear blessed with solar energy, draining the life of enemies.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 220, critRate: 0.12, critDamage: 0.25 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 2500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_WORLD_BREAKER',
    name: 'World Breaker',
    description: 'A celestial weapon forged from dying stars that shatters the dimensional fabric.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'MYTHIC',
    baseStats: { attack: 650, critRate: 0.25, critDamage: 0.5 },
    battlePerks: ['COSMIC_CATACLYSM'],
    isShopBuyable: false,
    shopPrice: 25000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: ARMOR ─────────────────────────────────────────────────────
  {
    code: 'ARMOR_IRON_HAUBERK',
    name: 'Iron Hauberk',
    description: 'Solid chainmail providing reliable protection in standard skirmishes.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 150, defense: 20 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 120,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_WOODEN_BUCKLER',
    name: 'Wooden Buckler',
    description: 'A light wooden shield reinforced with bronze bands.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 100, defense: 25, mitigation: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_DRAGONSCALE_PLATE',
    name: 'Dragonscale Plate',
    description: 'Impervious dragon scales that convert incoming impact into restorative essence.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SUPER_RARE',
    baseStats: { health: 800, defense: 90, mitigation: 0.08 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 3000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_AEGIS_BARRIER',
    name: 'Aegis Barrier',
    description: 'A legendary crystalline cuirass that freezes attackers upon impact.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1500, defense: 160, mitigation: 0.15 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 8000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: RELICS ────────────────────────────────────────────────────
  {
    code: 'RELIC_CHRONOS_HOURGLASS',
    name: 'Chronos Hourglass',
    description: 'Bends local time dilation to accelerate movements and freeze adversaries.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'ULTRA_RARE',
    baseStats: { speed: 45, elementalMastery: 0.15, manaShield: 200 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_PHOENIX_FEATHER',
    name: 'Phoenix Feather',
    description: 'An undying quill imbued with celestial fire that resurrects the fallen.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'SPECIAL_ILLUSTRATION_RARE',
    baseStats: { speed: 60, elementalMastery: 0.2, manaShield: 400 },
    battlePerks: ['PHOENIX_WARD'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: RINGS ────────────────────────────────────────────────────
  {
    code: 'RING_COPPER_BAND',
    name: 'Copper Band',
    description: 'A simple copper band that focuses martial intent.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'COMMON',
    baseStats: { attack: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'RING_BLAZING_SUN',
    name: 'Ring of the Blazing Sun',
    description: 'Infuses basic strikes with armor-piercing fiery heat.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'RARE',
    baseStats: { attack: 60, critRate: 0.06, armorPiercing: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: AMULETS ──────────────────────────────────────────────────
  {
    code: 'AMULET_LEATHER_CHOKER',
    name: 'Leather Choker',
    description: 'A sturdy leather choker blessed by local healers.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'COMMON',
    baseStats: { health: 120 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'AMULET_MOUNTAIN',
    name: 'Heart of the Mountain Amulet',
    description: 'Carved from granite bedrock to ward against elemental forces.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'RARE',
    baseStats: { health: 400, defense: 35, elementalResistance: 0.05 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: TALISMANS ────────────────────────────────────────────────
  {
    code: 'TALISMAN_SIMPLE_BANGLE',
    name: 'Simple Bangle',
    description: 'A lightweight silver-coated bangle providing modest poise.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'COMMON',
    baseStats: { defense: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_WINDWALKER',
    name: 'Windwalker Talisman',
    description: 'Harnesses atmospheric currents to boost speed and mana regeneration.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'RARE',
    baseStats: { speed: 25, manaMax: 20, manaRegen: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS & ACCESSORIES: BRACKET GEAR (dungeon drop tables) ──────────
  {
    code: 'RELIC_EMBER_CHARM',
    name: 'Ember Charm',
    description: 'A warm charm that soaks up the first sparks of a fight.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'COMMON',
    baseStats: { speed: 4, manaShield: 60 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 150,
    maxDailyPurchases: 3,
    isTradeable: true,
  },
  {
    code: 'ARMOR_MAGMA_MAIL',
    name: 'Magma-Forged Mail',
    description: 'Chainmail quenched in the crucible’s lower vents.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'RARE',
    baseStats: { health: 450, defense: 45, mitigation: 0.04 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_CINDER_LANTERN',
    name: 'Cinder Lantern',
    description: 'A lantern whose flame feeds its bearer’s mana.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'RARE',
    baseStats: { speed: 15, manaShield: 250, manaRegen: 0.05 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_PHOENIX_ASH_CENSER',
    name: 'Phoenix Ash Censer',
    description: 'Burning phoenix ash sharpens elemental strikes.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 25, manaShield: 450, elementalMastery: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SOLAR_FLARE',
    name: 'Solar Flare Ring',
    description: 'A band that flares hot enough to melt armor plates.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 100, critRate: 0.07, armorPiercing: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_OBSIDIAN_HEART',
    name: 'Obsidian Heart Amulet',
    description: 'Volcanic glass that hardens against elemental blasts.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'SUPER_RARE',
    baseStats: { health: 750, defense: 60, elementalResistance: 0.08 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_EMBERSTEP',
    name: 'Emberstep Talisman',
    description: 'Light as smoke; every step rekindles your mana.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 35, manaMax: 25, manaRegen: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRIMSON_CALAMITY',
    name: 'Crimson Calamity',
    description: 'A greatsword that leaves molten scars in the air.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 330, critRate: 0.12, critDamage: 0.3 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_INFERNO_CROWN',
    name: 'Inferno Crown Ring',
    description: 'Worn by the crucible’s old wardens.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 160, critRate: 0.1, armorPiercing: 0.15 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_MAGMA_CORE',
    name: 'Magma Core Amulet',
    description: 'A still-beating core of living magma.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1200, defense: 90, elementalResistance: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_TEMPEST_FEATHER',
    name: 'Tempest Feather',
    description: 'A feather that rides the heat currents.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'ULTRA_RARE',
    baseStats: { speed: 50, critRate: 0.05, manaRegen: 0.15 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_ETERNAL_CRUCIBLE',
    name: 'Eternal Crucible Plate',
    description: 'Plate forged in the crucible’s heart and never cooled.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SECRET_RARE',
    baseStats: { health: 2200, defense: 230, mitigation: 0.18 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SUNFORGED_SIGIL',
    name: 'Sunforged Sigil',
    description: 'A signet struck from the crucible’s first flame.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SECRET_RARE',
    baseStats: { attack: 230, critRate: 0.12, critDamage: 0.3 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_PRIMORDIAL_FLAME',
    name: 'Primordial Flame Amulet',
    description: 'Holds the flame that lit the tower.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'SECRET_RARE',
    baseStats: { health: 1800, defense: 140, elementalResistance: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_ASHEN_WINGS',
    name: 'Ashen Wings',
    description: 'Wings of ash that carry you above the flames.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SECRET_RARE',
    baseStats: { speed: 70, critRate: 0.08, manaRegen: 0.2 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── SEASON 1 BOSS SIGNATURE GEAR ──────────────────────────────────────────
  {
    code: 'RELIC_FIRE_BRIGADE_BADGE',
    name: 'Fire Brigade Badge',
    description:
      'Signature of Maki Oze (S1 F5). The badge of a firefighter who never gives ground.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'UNCOMMON',
    baseStats: { defense: 12, manaShield: 120, mitigation: 0.03 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 600,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRIMSON_CHANT_STAFF',
    name: 'Crimson Chant Staff',
    description: 'Signature of Megumin (S1 F10). Built for one enormous spell.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'RARE',
    baseStats: { attack: 95, critDamage: 0.3, elementalMastery: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_CRUSADER_PLATE',
    name: 'Unbreakable Crusader Plate',
    description: 'Signature of Darkness (S1 F15). Dented everywhere, broken nowhere.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'RARE',
    baseStats: { health: 550, defense: 55, mitigation: 0.06 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_MANEUVER_GEAR',
    name: 'Scorched Maneuver Gear',
    description: 'Signature of Mikasa Ackerman (S1 F20). Speed that cuts through armor.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 40, critRate: 0.06, armorPiercing: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SWORD_SAINT_BAND',
    name: 'Sword Saint Band',
    description: 'Signature of Eris Greyrat (S1 F25). For those who strike first.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 110, critRate: 0.08, critDamage: 0.2 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CALIDOS_GAUNTLETS',
    name: 'Calidos Gauntlets',
    description: 'Signature of Mereoleona Vermillion (S1 F30). Fists wreathed in wild flame.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 300, critRate: 0.1, armorPiercing: 0.15 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_HARVEST_POUCH',
    name: 'Wisewolf Harvest Pouch',
    description: 'Signature of Holo (S1 F35). A pouch of wheat that never runs dry.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1100, defense: 70, manaRegen: 0.08, elementalResistance: 0.08 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_RUIN_SIGNET',
    name: 'Signet of Ruin',
    description: 'Signature of Rias Gremory (S1 F40). Crimson power that consumes what it touches.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SECRET_RARE',
    baseStats: { attack: 200, critDamage: 0.35, elementalMastery: 0.2 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_CHAOS_DRAGON_SCALE',
    name: 'Chaos Dragon Scale',
    description: 'Signature of Tohru (S1 F45). A scale shed by a dragon in a hurry.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SECRET_RARE',
    baseStats: { health: 2400, defense: 240, mitigation: 0.18 },
    battlePerks: ['MANA_CONDUIT'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRUCIBLE_HEART_BLADE',
    name: 'Crucible Heart Blade',
    description: 'Signature of Shana (S1 F50). The flame at the summit, given an edge.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'MYTHIC',
    baseStats: { attack: 520, critRate: 0.18, critDamage: 0.4, elementalMastery: 0.25 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 50000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: HP POTIONS ───────────────────────────────────────────────
  {
    code: 'POTION_MINOR_HP',
    name: 'Minor HP Potion',
    description: 'Instantly restores 300 HP (or 25% max HP). Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'COMMON',
    consumableEffect: { healFlat: 300, healPercent: 0.25 },
    isShopBuyable: true,
    shopPrice: 50,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_MAJOR_HP',
    name: 'Major HP Potion',
    description: 'Instantly restores 1,200 HP (or 50% max HP). Crafted or found in dungeons.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'RARE',
    consumableEffect: { healFlat: 1200, healPercent: 0.5 },
    isShopBuyable: false,
    shopPrice: 200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_ELIXIR_VITALITY',
    name: 'Elixir of Full Vitality',
    description: 'Instantly restores 100% HP and clears all active debuffs and DoTs.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'ULTRA_RARE',
    consumableEffect: { healPercent: 1.0, cleanseDebuffs: true },
    isShopBuyable: false,
    shopPrice: 2000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: MANA POTIONS ─────────────────────────────────────────────
  {
    code: 'POTION_MANA_DRAUGHT',
    name: 'Mana Draught',
    description: 'Restores 30 MP needed for card active skills. Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'COMMON',
    consumableEffect: { restoreMp: 30 },
    isShopBuyable: true,
    shopPrice: 60,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_GREATER_MANA',
    name: 'Greater Mana Potion',
    description: 'Restores 70 MP. Mid-tier dungeon/quest reward.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'RARE',
    consumableEffect: { restoreMp: 70 },
    isShopBuyable: false,
    shopPrice: 250,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_COSMIC_ETHER',
    name: 'Cosmic Ether',
    description: 'Restores 100% MP and grants 1 instant free skill cast with zero cooldown.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { restoreMpPercent: 1.0, freeSkillCast: true },
    isShopBuyable: false,
    shopPrice: 5000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: ENERGY RESTORES ──────────────────────────────────────────
  {
    code: 'RESTORE_DAILY_ENERGY_BISCUIT',
    name: 'Daily Energy Biscuit',
    description:
      'A modest snack restoring +15 Energy. Strictly limited to 1 purchase per day in town.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'COMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: true,
    shopPrice: 300,
    maxDailyPurchases: 1,
    isTradeable: false,
  },
  {
    code: 'RESTORE_STAMINA_CANDY',
    name: 'Stamina Candy',
    description: 'A sweet energized candy restoring +15 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'UNCOMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: false,
    shopPrice: 350,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_GRAND_STAMINA_FLASK',
    name: 'Grand Stamina Flask',
    description: 'A concentrated tonic restoring +30 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'RARE',
    consumableEffect: { energyRestored: 30 },
    isShopBuyable: false,
    shopPrice: 800,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_CELESTIAL_AMBROSIA',
    name: 'Celestial Ambrosia',
    description: 'Divine nectar that fully replenishes energy up to the summoner level cap.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { fullEnergyRestore: true },
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: false,
  },

  // ─── MATERIALS ─────────────────────────────────────────────────────────────
  {
    code: 'CRAFTING_DUST',
    name: 'Crafting Dust',
    description:
      'Shimmering residue from dismantled cards and cleared floors. Spent to enhance equipment or craft new gear and potions.',
    type: 'MATERIAL',
    subtype: 'CRAFTING_DUST',
    rarity: 'COMMON',
    isShopBuyable: false,
    shopPrice: 0,
    maxDailyPurchases: 0,
    isTradeable: false,
  },
];

/**
 * Drop-only RARE gear that the Town Shop may stock for a day (see TcgShopService.getDailyRotation).
 * Boss signature gear is never listed here, so it stays a reward for beating the boss.
 */
export const DAILY_ROTATION_POOL: readonly string[] = [
  'WEAPON_OBSIDIAN_KATANA',
  'ARMOR_MAGMA_MAIL',
  'RELIC_CINDER_LANTERN',
  'RING_BLAZING_SUN',
  'AMULET_MOUNTAIN',
  'TALISMAN_WINDWALKER',
];

/** Catalog code of the enhancement currency. */
export const CRAFTING_DUST_CODE = 'CRAFTING_DUST';

/**
 * Canonical item UUIDs pinned for database stability.
 * Prevents foreign key orphanage in `user_inventory_items` if `game_items` is ever recreated.
 */
export const CANONICAL_ITEM_IDS: Readonly<Record<string, string>> = Object.freeze({
  AMULET_HARVEST_POUCH: '428f3185-8324-449a-9e69-e017997c92eb',
  AMULET_LEATHER_CHOKER: 'eaf3923c-da28-4de9-89a1-6b6c8a26621a',
  AMULET_MAGMA_CORE: '82df1934-064d-45a3-a833-f99f973d78e6',
  AMULET_MOUNTAIN: '4fc9fb95-1428-4a06-ace9-3691429aedb4',
  AMULET_OBSIDIAN_HEART: 'd99ff9f2-371e-4d28-9460-c3cbe110a141',
  AMULET_PRIMORDIAL_FLAME: 'f268518d-fc57-4192-aadc-b28126aa8b8c',
  ARMOR_AEGIS_BARRIER: '15d7d3dc-72dd-407b-97c1-35dae593b866',
  ARMOR_CHAOS_DRAGON_SCALE: '62a25e14-2a37-40ca-bc28-a5536f1a8046',
  ARMOR_CRUSADER_PLATE: 'd7504b5a-39b6-4721-8f29-8c1d7f8c2731',
  ARMOR_DRAGONSCALE_PLATE: 'ba74fa00-e690-4d61-b8eb-d5aba1688acc',
  ARMOR_ETERNAL_CRUCIBLE: '39401836-2515-4c9f-9e4c-157fe8dc22af',
  ARMOR_IRON_HAUBERK: 'c4aabfc1-2bd9-4859-b5cc-67fa147ad61c',
  ARMOR_MAGMA_MAIL: 'a67ec9bc-4a9d-4c37-84fc-0a49ffd3db3f',
  ARMOR_WOODEN_BUCKLER: 'abbd578e-fc5e-452c-848a-7aa74152df2f',
  CRAFTING_DUST: 'f3e71427-7629-4edd-8a25-e3dc375a9224',
  POTION_COSMIC_ETHER: '2cdefda2-afc3-4258-915f-c2a559af945a',
  POTION_ELIXIR_VITALITY: '8c5b3e05-662c-4a06-9344-0ea6ff0b9502',
  POTION_GREATER_MANA: '0d0bf3a6-98d2-4a63-89c7-b8f0ee42715a',
  POTION_MAJOR_HP: 'c85e0f7b-2431-40f8-845a-02d6ba9bfd88',
  POTION_MANA_DRAUGHT: '780208b7-388e-444e-845f-4e2af85939bd',
  POTION_MINOR_HP: 'f2e5d93e-842f-4cbc-baac-d37b96f2c743',
  RELIC_CHRONOS_HOURGLASS: '55cd33e2-95f2-4d49-af65-4f18d009a802',
  RELIC_CINDER_LANTERN: 'cdb53932-536f-404e-bb89-a8be5926588c',
  RELIC_EMBER_CHARM: '64d0d72a-1d48-43a0-b9be-522d8a47d99e',
  RELIC_FIRE_BRIGADE_BADGE: '3527440b-a694-4281-bbbe-bd83d6f31630',
  RELIC_PHOENIX_ASH_CENSER: '4b3bc381-7d27-4ca9-ad2f-30291fdf70d8',
  RELIC_PHOENIX_FEATHER: '5e7bfcfa-7d47-45f2-9cbf-dec171986ce6',
  RESTORE_CELESTIAL_AMBROSIA: '27c8ab94-2392-4922-aa91-0d7d5dd16bf7',
  RESTORE_DAILY_ENERGY_BISCUIT: 'ad22cc2e-79eb-4fd9-a63c-a180dfdab754',
  RESTORE_GRAND_STAMINA_FLASK: 'c10a63c0-d2f9-4373-9936-7cd9a55f17de',
  RESTORE_STAMINA_CANDY: '7278c6cf-fb2b-42df-84d7-c0132c7ba1b6',
  RING_BLAZING_SUN: '97fb2297-f3da-40c9-803f-c1844e3cd7bd',
  RING_COPPER_BAND: '242f58f8-790d-45dc-9381-22699f7ad0f8',
  RING_INFERNO_CROWN: '6139aa14-afd7-445a-ab46-1dacb60eee6a',
  RING_RUIN_SIGNET: '3df59bab-9c9c-4a64-aad2-d0c940d80f73',
  RING_SOLAR_FLARE: '59adcf7c-e45b-4638-8555-d3308b3953ed',
  RING_SUNFORGED_SIGIL: 'c6788630-c5ea-4a55-984a-bf939fae24c1',
  RING_SWORD_SAINT_BAND: '379c5d3f-b079-4a28-8ffc-90377ee1bb88',
  TALISMAN_ASHEN_WINGS: '1c7ebfbe-6d44-412d-a019-8e4daa0dfe4e',
  TALISMAN_EMBERSTEP: '35ca6b54-7e48-4fd3-a44b-f92a76e509e8',
  TALISMAN_MANEUVER_GEAR: 'b7ab73b1-3f47-46f1-945c-2995b7d1b106',
  TALISMAN_SIMPLE_BANGLE: 'efda3337-ff9b-4ad1-ba1b-a1ac334e0577',
  TALISMAN_TEMPEST_FEATHER: '2f2ba597-6570-498a-8319-181375c31ba2',
  TALISMAN_WINDWALKER: '3916b750-8a6b-46b0-ae21-2d094e17e50b',
  WEAPON_CALIDOS_GAUNTLETS: '4558eeaf-c26b-4383-883d-04aec69373f6',
  WEAPON_CRIMSON_CALAMITY: '2fa58ede-7220-497f-8bb8-1e0458ff111d',
  WEAPON_CRIMSON_CHANT_STAFF: '5b163937-0287-4335-8b64-da486240db10',
  WEAPON_CRUCIBLE_HEART_BLADE: 'cbba6355-1fd3-4981-a78a-ddeb0168b1f5',
  WEAPON_NOVICE_BLADE: '10f39f7a-2bcd-43c9-ac33-82a12942b14d',
  WEAPON_OBSIDIAN_KATANA: 'e8520124-bdff-4461-bcf6-2fddddcfefb1',
  WEAPON_SCOUT_BOOMERANG: '1ef80637-76b2-419b-ba3f-e69345b0c0f0',
  WEAPON_SOLAR_LANCE: 'a3a82789-5257-4bf7-9387-2348361f21fb',
  WEAPON_WORLD_BREAKER: '97e956d5-7bb6-44fe-9052-fd049ab8a081',
});

/**
 * Synchronizes canonical item definitions to the database.
 * Creates items that don't exist yet with stable UUIDs, and updates existing rows with
 * catalog-owned fields while preserving existing UUIDs.
 * The shop fields (isShopBuyable, shopPrice, maxDailyPurchases) of a row the owner console
 * edited (`ownerOverridden`) are kept, so an owner's price survives a bot restart.
 */
export async function syncCanonicalItems(
  itemRepo: GameItemRepository,
  items: readonly NewGameItem[] = CANONICAL_ITEMS,
): Promise<{ created: number; updated: number }> {
  let created = 0;
  let updated = 0;

  for (const item of items) {
    const exists = await itemRepo.findByCode(item.code);
    if (!exists) {
      const stableId = item.id ?? CANONICAL_ITEM_IDS[item.code];
      await itemRepo.create({
        ...item,
        ...(stableId ? { id: stableId } : {}),
      });
      created++;
    } else {
      await itemRepo.update(exists.id, {
        name: item.name,
        description: item.description,
        type: item.type,
        subtype: item.subtype,
        rarity: item.rarity,
        baseStats: item.baseStats ?? {},
        battlePerks: item.battlePerks ?? [],
        consumableEffect: item.consumableEffect ?? {},
        ...(exists.ownerOverridden
          ? {}
          : {
              isShopBuyable: item.isShopBuyable ?? true,
              shopPrice: item.shopPrice ?? 100,
              maxDailyPurchases: item.maxDailyPurchases ?? 5,
            }),
        isTradeable: item.isTradeable ?? true,
      });
      updated++;
    }
  }

  return { created, updated };
}
