import type { NewGameItem, GameItemRepository } from '@ririko/database';

export const CANONICAL_ITEMS: NewGameItem[] = [
  // ─── EQUIPMENTS: WEAPONS ───────────────────────────────────────────────────
  {
    code: 'WEAPON_NOVICE_BLADE',
    name: 'Novice Blade',
    description: 'A standard starter training sword forged for new summoners.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'COMMON',
    baseStats: { attack: 25, critRate: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SCOUT_BOOMERANG',
    name: 'Scout Boomerang',
    description: 'A swift, balanced curved blade that returns to its wielder with agility.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'UNCOMMON',
    baseStats: { attack: 45, speed: 5, critRate: 0.03 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 250,
    maxDailyPurchases: 3,
    isTradeable: true,
  },
  {
    code: 'WEAPON_OBSIDIAN_KATANA',
    name: 'Obsidian Katana',
    description: 'A razor-sharp volcanic blade that punctures hardened defenses with ease.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'RARE',
    baseStats: { attack: 110, critRate: 0.08, critDamage: 0.15 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 1000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SOLAR_LANCE',
    name: 'Solar Lance',
    description: 'A radiant spear blessed with solar energy, draining the life of enemies.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 220, critRate: 0.12, critDamage: 0.25 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 2500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_WORLD_BREAKER',
    name: 'World Breaker',
    description: 'A celestial weapon forged from dying stars that shatters the dimensional fabric.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'MYTHIC',
    baseStats: { attack: 650, critRate: 0.25, critDamage: 0.5 },
    battlePerks: ['COSMIC_CATACLYSM'],
    isShopBuyable: false,
    shopPrice: 25000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: ARMOR ─────────────────────────────────────────────────────
  {
    code: 'ARMOR_IRON_HAUBERK',
    name: 'Iron Hauberk',
    description: 'Solid chainmail providing reliable protection in standard skirmishes.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 150, defense: 20 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 120,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_WOODEN_BUCKLER',
    name: 'Wooden Buckler',
    description: 'A light wooden shield reinforced with bronze bands.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 100, defense: 25, mitigation: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_DRAGONSCALE_PLATE',
    name: 'Dragonscale Plate',
    description: 'Impervious dragon scales that convert incoming impact into restorative essence.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SUPER_RARE',
    baseStats: { health: 800, defense: 90, mitigation: 0.08 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 3000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_AEGIS_BARRIER',
    name: 'Aegis Barrier',
    description: 'A legendary crystalline cuirass that freezes attackers upon impact.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1500, defense: 160, mitigation: 0.15 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 8000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: RELICS ────────────────────────────────────────────────────
  {
    code: 'RELIC_CHRONOS_HOURGLASS',
    name: 'Chronos Hourglass',
    description: 'Bends local time dilation to accelerate movements and freeze adversaries.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'ULTRA_RARE',
    baseStats: { speed: 45, elementalMastery: 0.15, manaShield: 200 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_PHOENIX_FEATHER',
    name: 'Phoenix Feather',
    description: 'An undying quill imbued with celestial fire that resurrects the fallen.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'SPECIAL_ILLUSTRATION_RARE',
    baseStats: { speed: 60, elementalMastery: 0.2, manaShield: 400 },
    battlePerks: ['PHOENIX_WARD'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: RINGS ────────────────────────────────────────────────────
  {
    code: 'RING_COPPER_BAND',
    name: 'Copper Band',
    description: 'A simple copper band that focuses martial intent.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'COMMON',
    baseStats: { attack: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'RING_BLAZING_SUN',
    name: 'Ring of the Blazing Sun',
    description: 'Infuses basic strikes with armor-piercing fiery heat.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'RARE',
    baseStats: { attack: 60, critRate: 0.06, armorPiercing: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: AMULETS ──────────────────────────────────────────────────
  {
    code: 'AMULET_LEATHER_CHOKER',
    name: 'Leather Choker',
    description: 'A sturdy leather choker blessed by local healers.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'COMMON',
    baseStats: { health: 120 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'AMULET_MOUNTAIN',
    name: 'Heart of the Mountain Amulet',
    description: 'Carved from granite bedrock to ward against elemental forces.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'RARE',
    baseStats: { health: 400, defense: 35, elementalResistance: 0.05 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: TALISMANS ────────────────────────────────────────────────
  {
    code: 'TALISMAN_SIMPLE_BANGLE',
    name: 'Simple Bangle',
    description: 'A lightweight silver-coated bangle providing modest poise.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'COMMON',
    baseStats: { defense: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_WINDWALKER',
    name: 'Windwalker Talisman',
    description: 'Harnesses atmospheric currents to boost speed and mana regeneration.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'RARE',
    baseStats: { speed: 25, manaMax: 20, manaRegen: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS & ACCESSORIES: BRACKET GEAR (dungeon drop tables) ──────────
  {
    code: 'RELIC_EMBER_CHARM',
    name: 'Ember Charm',
    description: 'A warm charm that soaks up the first sparks of a fight.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'COMMON',
    baseStats: { speed: 4, manaShield: 60 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 150,
    maxDailyPurchases: 3,
    isTradeable: true,
  },
  {
    code: 'ARMOR_MAGMA_MAIL',
    name: 'Magma-Forged Mail',
    description: 'Chainmail quenched in the crucible’s lower vents.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'RARE',
    baseStats: { health: 450, defense: 45, mitigation: 0.04 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_CINDER_LANTERN',
    name: 'Cinder Lantern',
    description: 'A lantern whose flame feeds its bearer’s mana.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'RARE',
    baseStats: { speed: 15, manaShield: 250, manaRegen: 0.05 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_PHOENIX_ASH_CENSER',
    name: 'Phoenix Ash Censer',
    description: 'Burning phoenix ash sharpens elemental strikes.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 25, manaShield: 450, elementalMastery: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SOLAR_FLARE',
    name: 'Solar Flare Ring',
    description: 'A band that flares hot enough to melt armor plates.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 100, critRate: 0.07, armorPiercing: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_OBSIDIAN_HEART',
    name: 'Obsidian Heart Amulet',
    description: 'Volcanic glass that hardens against elemental blasts.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'SUPER_RARE',
    baseStats: { health: 750, defense: 60, elementalResistance: 0.08 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_EMBERSTEP',
    name: 'Emberstep Talisman',
    description: 'Light as smoke; every step rekindles your mana.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 35, manaMax: 25, manaRegen: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRIMSON_CALAMITY',
    name: 'Crimson Calamity',
    description: 'A greatsword that leaves molten scars in the air.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 330, critRate: 0.12, critDamage: 0.3 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_INFERNO_CROWN',
    name: 'Inferno Crown Ring',
    description: 'Worn by the crucible’s old wardens.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 160, critRate: 0.1, armorPiercing: 0.15 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_MAGMA_CORE',
    name: 'Magma Core Amulet',
    description: 'A still-beating core of living magma.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1200, defense: 90, elementalResistance: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_TEMPEST_FEATHER',
    name: 'Tempest Feather',
    description: 'A feather that rides the heat currents.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'ULTRA_RARE',
    baseStats: { speed: 50, critRate: 0.05, manaRegen: 0.15 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_ETERNAL_CRUCIBLE',
    name: 'Eternal Crucible Plate',
    description: 'Plate forged in the crucible’s heart and never cooled.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SECRET_RARE',
    baseStats: { health: 2200, defense: 230, mitigation: 0.18 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SUNFORGED_SIGIL',
    name: 'Sunforged Sigil',
    description: 'A signet struck from the crucible’s first flame.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SECRET_RARE',
    baseStats: { attack: 230, critRate: 0.12, critDamage: 0.3 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_PRIMORDIAL_FLAME',
    name: 'Primordial Flame Amulet',
    description: 'Holds the flame that lit the tower.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'SECRET_RARE',
    baseStats: { health: 1800, defense: 140, elementalResistance: 0.12 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_ASHEN_WINGS',
    name: 'Ashen Wings',
    description: 'Wings of ash that carry you above the flames.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SECRET_RARE',
    baseStats: { speed: 70, critRate: 0.08, manaRegen: 0.2 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── SEASON 1 BOSS SIGNATURE GEAR ──────────────────────────────────────────
  {
    code: 'RELIC_FIRE_BRIGADE_BADGE',
    name: 'Fire Brigade Badge',
    description:
      'Signature of Maki Oze (S1 F5). The badge of a firefighter who never gives ground.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'UNCOMMON',
    baseStats: { defense: 12, manaShield: 120, mitigation: 0.03 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 600,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRIMSON_CHANT_STAFF',
    name: 'Crimson Chant Staff',
    description: 'Signature of Megumin (S1 F10). Built for one enormous spell.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'RARE',
    baseStats: { attack: 95, critDamage: 0.3, elementalMastery: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_CRUSADER_PLATE',
    name: 'Unbreakable Crusader Plate',
    description: 'Signature of Darkness (S1 F15). Dented everywhere, broken nowhere.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'RARE',
    baseStats: { health: 550, defense: 55, mitigation: 0.06 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_MANEUVER_GEAR',
    name: 'Scorched Maneuver Gear',
    description: 'Signature of Mikasa Ackerman (S1 F20). Speed that cuts through armor.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'SUPER_RARE',
    baseStats: { speed: 40, critRate: 0.06, armorPiercing: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_SWORD_SAINT_BAND',
    name: 'Sword Saint Band',
    description: 'Signature of Eris Greyrat (S1 F25). For those who strike first.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 110, critRate: 0.08, critDamage: 0.2 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 4000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CALIDOS_GAUNTLETS',
    name: 'Calidos Gauntlets',
    description: 'Signature of Mereoleona Vermillion (S1 F30). Fists wreathed in wild flame.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'ULTRA_RARE',
    baseStats: { attack: 300, critRate: 0.1, armorPiercing: 0.15 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'AMULET_HARVEST_POUCH',
    name: 'Wisewolf Harvest Pouch',
    description: 'Signature of Holo (S1 F35). A pouch of wheat that never runs dry.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1100, defense: 70, manaRegen: 0.08, elementalResistance: 0.08 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RING_RUIN_SIGNET',
    name: 'Signet of Ruin',
    description: 'Signature of Rias Gremory (S1 F40). Crimson power that consumes what it touches.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'SECRET_RARE',
    baseStats: { attack: 200, critDamage: 0.35, elementalMastery: 0.2 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_CHAOS_DRAGON_SCALE',
    name: 'Chaos Dragon Scale',
    description: 'Signature of Tohru (S1 F45). A scale shed by a dragon in a hurry.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SECRET_RARE',
    baseStats: { health: 2400, defense: 240, mitigation: 0.18 },
    battlePerks: ['MANA_CONDUIT'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_CRUCIBLE_HEART_BLADE',
    name: 'Crucible Heart Blade',
    description: 'Signature of Shana (S1 F50). The flame at the summit, given an edge.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'MYTHIC',
    baseStats: { attack: 520, critRate: 0.18, critDamage: 0.4, elementalMastery: 0.25 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 50000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: HP POTIONS ───────────────────────────────────────────────
  {
    code: 'POTION_MINOR_HP',
    name: 'Minor HP Potion',
    description: 'Instantly restores 300 HP (or 25% max HP). Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'COMMON',
    consumableEffect: { healFlat: 300, healPercent: 0.25 },
    isShopBuyable: true,
    shopPrice: 50,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_MAJOR_HP',
    name: 'Major HP Potion',
    description: 'Instantly restores 1,200 HP (or 50% max HP). Crafted or found in dungeons.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'RARE',
    consumableEffect: { healFlat: 1200, healPercent: 0.5 },
    isShopBuyable: false,
    shopPrice: 200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_ELIXIR_VITALITY',
    name: 'Elixir of Full Vitality',
    description: 'Instantly restores 100% HP and clears all active debuffs and DoTs.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'ULTRA_RARE',
    consumableEffect: { healPercent: 1.0, cleanseDebuffs: true },
    isShopBuyable: false,
    shopPrice: 2000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: MANA POTIONS ─────────────────────────────────────────────
  {
    code: 'POTION_MANA_DRAUGHT',
    name: 'Mana Draught',
    description: 'Restores 30 MP needed for card active skills. Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'COMMON',
    consumableEffect: { restoreMp: 30 },
    isShopBuyable: true,
    shopPrice: 60,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_GREATER_MANA',
    name: 'Greater Mana Potion',
    description: 'Restores 70 MP. Mid-tier dungeon/quest reward.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'RARE',
    consumableEffect: { restoreMp: 70 },
    isShopBuyable: false,
    shopPrice: 250,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_COSMIC_ETHER',
    name: 'Cosmic Ether',
    description: 'Restores 100% MP and grants 1 instant free skill cast with zero cooldown.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { restoreMpPercent: 1.0, freeSkillCast: true },
    isShopBuyable: false,
    shopPrice: 5000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: ENERGY RESTORES ──────────────────────────────────────────
  {
    code: 'RESTORE_DAILY_ENERGY_BISCUIT',
    name: 'Daily Energy Biscuit',
    description:
      'A modest snack restoring +15 Energy. Strictly limited to 1 purchase per day in town.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'COMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: true,
    shopPrice: 300,
    maxDailyPurchases: 1,
    isTradeable: false,
  },
  {
    code: 'RESTORE_STAMINA_CANDY',
    name: 'Stamina Candy',
    description: 'A sweet energized candy restoring +15 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'UNCOMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: false,
    shopPrice: 350,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_GRAND_STAMINA_FLASK',
    name: 'Grand Stamina Flask',
    description: 'A concentrated tonic restoring +30 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'RARE',
    consumableEffect: { energyRestored: 30 },
    isShopBuyable: false,
    shopPrice: 800,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_CELESTIAL_AMBROSIA',
    name: 'Celestial Ambrosia',
    description: 'Divine nectar that fully replenishes energy up to the summoner level cap.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { fullEnergyRestore: true },
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: false,
  },

  // ─── MATERIALS ─────────────────────────────────────────────────────────────
  {
    code: 'CRAFTING_DUST',
    name: 'Crafting Dust',
    description:
      'Shimmering residue from dismantled cards and cleared floors. Spent to enhance equipment or craft new gear and potions.',
    type: 'MATERIAL',
    subtype: 'CRAFTING_DUST',
    rarity: 'COMMON',
    isShopBuyable: false,
    shopPrice: 0,
    maxDailyPurchases: 0,
    isTradeable: false,
  },
];

/**
 * Drop-only RARE gear that the Town Shop may stock for a day (see TcgShopService.getDailyRotation).
 * Boss signature gear is never listed here, so it stays a reward for beating the boss.
 */
export const DAILY_ROTATION_POOL: readonly string[] = [
  'WEAPON_OBSIDIAN_KATANA',
  'ARMOR_MAGMA_MAIL',
  'RELIC_CINDER_LANTERN',
  'RING_BLAZING_SUN',
  'AMULET_MOUNTAIN',
  'TALISMAN_WINDWALKER',
];

/** Catalog code of the enhancement currency. */
export const CRAFTING_DUST_CODE = 'CRAFTING_DUST';

/**
 * Synchronizes canonical item definitions to the database.
 * Creates items that don't exist yet, and updates existing rows with catalog-owned fields
 * (name, description, type, subtype, rarity, baseStats, battlePerks, consumableEffect,
 * isShopBuyable, shopPrice, maxDailyPurchases, isTradeable) while preserving existing UUIDs.
 */
export async function syncCanonicalItems(
  itemRepo: GameItemRepository,
  items: readonly NewGameItem[] = CANONICAL_ITEMS,
): Promise<{ created: number; updated: number }> {
  let created = 0;
  let updated = 0;

  for (const item of items) {
    const exists = await itemRepo.findByCode(item.code);
    if (!exists) {
      await itemRepo.create(item);
      created++;
    } else {
      await itemRepo.update(exists.id, {
        name: item.name,
        description: item.description,
        type: item.type,
        subtype: item.subtype,
        rarity: item.rarity,
        baseStats: item.baseStats ?? {},
        battlePerks: item.battlePerks ?? [],
        consumableEffect: item.consumableEffect ?? {},
        isShopBuyable: item.isShopBuyable ?? true,
        shopPrice: item.shopPrice ?? 100,
        maxDailyPurchases: item.maxDailyPurchases ?? 5,
        isTradeable: item.isTradeable ?? true,
      });
      updated++;
    }
  }

  return { created, updated };
}
