import type { NewGameItem } from '@ririko/database';

export const CANONICAL_ITEMS: NewGameItem[] = [
  // ─── EQUIPMENTS: WEAPONS ───────────────────────────────────────────────────
  {
    code: 'WEAPON_NOVICE_BLADE',
    name: 'Novice Blade',
    description: 'A standard starter training sword forged for new summoners.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'COMMON',
    baseStats: { attack: 25, critRate: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SCOUT_BOOMERANG',
    name: 'Scout Boomerang',
    description: 'A swift, balanced curved blade that returns to its wielder with agility.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'UNCOMMON',
    baseStats: { attack: 45, speed: 5, critRate: 0.03 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 250,
    maxDailyPurchases: 3,
    isTradeable: true,
  },
  {
    code: 'WEAPON_OBSIDIAN_KATANA',
    name: 'Obsidian Katana',
    description: 'A razor-sharp volcanic blade that punctures hardened defenses with ease.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'RARE',
    baseStats: { attack: 110, critRate: 0.08, critDamage: 0.15 },
    battlePerks: ['SHARPENED_EDGE'],
    isShopBuyable: false,
    shopPrice: 1000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_SOLAR_LANCE',
    name: 'Solar Lance',
    description: 'A radiant spear blessed with solar energy, draining the life of enemies.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'SUPER_RARE',
    baseStats: { attack: 220, critRate: 0.12, critDamage: 0.25 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 2500,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'WEAPON_WORLD_BREAKER',
    name: 'World Breaker',
    description: 'A celestial weapon forged from dying stars that shatters the dimensional fabric.',
    type: 'EQUIPMENT',
    subtype: 'WEAPON',
    rarity: 'MYTHIC',
    baseStats: { attack: 650, critRate: 0.25, critDamage: 0.5 },
    battlePerks: ['COSMIC_CATACLYSM'],
    isShopBuyable: false,
    shopPrice: 25000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: ARMOR ─────────────────────────────────────────────────────
  {
    code: 'ARMOR_IRON_HAUBERK',
    name: 'Iron Hauberk',
    description: 'Solid chainmail providing reliable protection in standard skirmishes.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 150, defense: 20 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 120,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_WOODEN_BUCKLER',
    name: 'Wooden Buckler',
    description: 'A light wooden shield reinforced with bronze bands.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'COMMON',
    baseStats: { health: 100, defense: 25, mitigation: 0.02 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 100,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'ARMOR_DRAGONSCALE_PLATE',
    name: 'Dragonscale Plate',
    description: 'Impervious dragon scales that convert incoming impact into restorative essence.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'SUPER_RARE',
    baseStats: { health: 800, defense: 90, mitigation: 0.08 },
    battlePerks: ['VAMPIRIC_TOUCH'],
    isShopBuyable: false,
    shopPrice: 3000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'ARMOR_AEGIS_BARRIER',
    name: 'Aegis Barrier',
    description: 'A legendary crystalline cuirass that freezes attackers upon impact.',
    type: 'EQUIPMENT',
    subtype: 'ARMOR',
    rarity: 'ULTRA_RARE',
    baseStats: { health: 1500, defense: 160, mitigation: 0.15 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 8000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── EQUIPMENTS: RELICS ────────────────────────────────────────────────────
  {
    code: 'RELIC_CHRONOS_HOURGLASS',
    name: 'Chronos Hourglass',
    description: 'Bends local time dilation to accelerate movements and freeze adversaries.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'ULTRA_RARE',
    baseStats: { speed: 45, elementalMastery: 0.15, manaShield: 200 },
    battlePerks: ['GLACIAL_COUNTER'],
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RELIC_PHOENIX_FEATHER',
    name: 'Phoenix Feather',
    description: 'An undying quill imbued with celestial fire that resurrects the fallen.',
    type: 'EQUIPMENT',
    subtype: 'RELIC',
    rarity: 'SPECIAL_ILLUSTRATION_RARE',
    baseStats: { speed: 60, elementalMastery: 0.2, manaShield: 400 },
    battlePerks: ['PHOENIX_WARD'],
    isShopBuyable: false,
    shopPrice: 20000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: RINGS ────────────────────────────────────────────────────
  {
    code: 'RING_COPPER_BAND',
    name: 'Copper Band',
    description: 'A simple copper band that focuses martial intent.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'COMMON',
    baseStats: { attack: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'RING_BLAZING_SUN',
    name: 'Ring of the Blazing Sun',
    description: 'Infuses basic strikes with armor-piercing fiery heat.',
    type: 'ACCESSORY',
    subtype: 'RING',
    rarity: 'RARE',
    baseStats: { attack: 60, critRate: 0.06, armorPiercing: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: AMULETS ──────────────────────────────────────────────────
  {
    code: 'AMULET_LEATHER_CHOKER',
    name: 'Leather Choker',
    description: 'A sturdy leather choker blessed by local healers.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'COMMON',
    baseStats: { health: 120 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'AMULET_MOUNTAIN',
    name: 'Heart of the Mountain Amulet',
    description: 'Carved from granite bedrock to ward against elemental forces.',
    type: 'ACCESSORY',
    subtype: 'AMULET',
    rarity: 'RARE',
    baseStats: { health: 400, defense: 35, elementalResistance: 0.05 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── ACCESSORIES: TALISMANS ────────────────────────────────────────────────
  {
    code: 'TALISMAN_SIMPLE_BANGLE',
    name: 'Simple Bangle',
    description: 'A lightweight silver-coated bangle providing modest poise.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'COMMON',
    baseStats: { defense: 15 },
    battlePerks: [],
    isShopBuyable: true,
    shopPrice: 80,
    maxDailyPurchases: 5,
    isTradeable: true,
  },
  {
    code: 'TALISMAN_WINDWALKER',
    name: 'Windwalker Talisman',
    description: 'Harnesses atmospheric currents to boost speed and mana regeneration.',
    type: 'ACCESSORY',
    subtype: 'TALISMAN',
    rarity: 'RARE',
    baseStats: { speed: 25, manaMax: 20, manaRegen: 0.1 },
    battlePerks: [],
    isShopBuyable: false,
    shopPrice: 1200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: HP POTIONS ───────────────────────────────────────────────
  {
    code: 'POTION_MINOR_HP',
    name: 'Minor HP Potion',
    description: 'Instantly restores 300 HP (or 25% max HP). Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'COMMON',
    consumableEffect: { healFlat: 300, healPercent: 0.25 },
    isShopBuyable: true,
    shopPrice: 50,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_MAJOR_HP',
    name: 'Major HP Potion',
    description: 'Instantly restores 1,200 HP (or 50% max HP). Crafted or found in dungeons.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'RARE',
    consumableEffect: { healFlat: 1200, healPercent: 0.5 },
    isShopBuyable: false,
    shopPrice: 200,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_ELIXIR_VITALITY',
    name: 'Elixir of Full Vitality',
    description: 'Instantly restores 100% HP and clears all active debuffs and DoTs.',
    type: 'CONSUMABLE',
    subtype: 'HP_POTION',
    rarity: 'ULTRA_RARE',
    consumableEffect: { healPercent: 1.0, cleanseDebuffs: true },
    isShopBuyable: false,
    shopPrice: 2000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: MANA POTIONS ─────────────────────────────────────────────
  {
    code: 'POTION_MANA_DRAUGHT',
    name: 'Mana Draught',
    description: 'Restores 30 MP needed for card active skills. Sold in basic town shop.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'COMMON',
    consumableEffect: { restoreMp: 30 },
    isShopBuyable: true,
    shopPrice: 60,
    maxDailyPurchases: 10,
    isTradeable: true,
  },
  {
    code: 'POTION_GREATER_MANA',
    name: 'Greater Mana Potion',
    description: 'Restores 70 MP. Mid-tier dungeon/quest reward.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'RARE',
    consumableEffect: { restoreMp: 70 },
    isShopBuyable: false,
    shopPrice: 250,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'POTION_COSMIC_ETHER',
    name: 'Cosmic Ether',
    description: 'Restores 100% MP and grants 1 instant free skill cast with zero cooldown.',
    type: 'CONSUMABLE',
    subtype: 'MANA_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { restoreMpPercent: 1.0, freeSkillCast: true },
    isShopBuyable: false,
    shopPrice: 5000,
    maxDailyPurchases: 0,
    isTradeable: true,
  },

  // ─── CONSUMABLES: ENERGY RESTORES ──────────────────────────────────────────
  {
    code: 'RESTORE_DAILY_ENERGY_BISCUIT',
    name: 'Daily Energy Biscuit',
    description: 'A modest snack restoring +15 Energy. Strictly limited to 1 purchase per day in town.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'COMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: true,
    shopPrice: 300,
    maxDailyPurchases: 1,
    isTradeable: false,
  },
  {
    code: 'RESTORE_STAMINA_CANDY',
    name: 'Stamina Candy',
    description: 'A sweet energized candy restoring +15 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'UNCOMMON',
    consumableEffect: { energyRestored: 15 },
    isShopBuyable: false,
    shopPrice: 350,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_GRAND_STAMINA_FLASK',
    name: 'Grand Stamina Flask',
    description: 'A concentrated tonic restoring +30 Energy.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'RARE',
    consumableEffect: { energyRestored: 30 },
    isShopBuyable: false,
    shopPrice: 800,
    maxDailyPurchases: 0,
    isTradeable: true,
  },
  {
    code: 'RESTORE_CELESTIAL_AMBROSIA',
    name: 'Celestial Ambrosia',
    description: 'Divine nectar that fully replenishes energy up to the summoner level cap.',
    type: 'CONSUMABLE',
    subtype: 'ENERGY_POTION',
    rarity: 'MYTHIC',
    consumableEffect: { fullEnergyRestore: true },
    isShopBuyable: false,
    shopPrice: 10000,
    maxDailyPurchases: 0,
    isTradeable: false,
  },
];
