import type { NewGameAchievement } from '@ririko/database';

export const CANONICAL_ACHIEVEMENTS: NewGameAchievement[] = [
  {
    code: 'COLL_INITIATE',
    title: 'Card Initiate',
    description: 'Collect 10 unique cards in your collection.',
    category: 'COLLECTOR',
    tier: 'BRONZE',
    requirementType: 'CARD_COUNT',
    requirementTarget: 10,
    rewardXp: 500,
    rewardCredits: 1000,
    rewardConsumables: { potion_hp_minor: 2 },
    badgeIcon: '🎴',
  },
  {
    code: 'COLL_ELEMENTAL',
    title: 'Elemental Harmony',
    description: 'Collect at least 1 card of each of the 7 elemental affinities.',
    category: 'COLLECTOR',
    tier: 'SILVER',
    requirementType: 'ELEMENTAL_COUNT',
    requirementTarget: 7,
    rewardXp: 1500,
    rewardCredits: 5000,
    rewardTitle: 'Prismatic Adept',
    badgeIcon: '🌈',
  },
  {
    code: 'COLL_MYTHIC_LEGEND',
    title: 'Mythic Ascension',
    description: 'Summon or synthesize at least 1 Mythic tier card.',
    category: 'COLLECTOR',
    tier: 'MYTHIC',
    requirementType: 'MYTHIC_CARD_COUNT',
    requirementTarget: 1,
    rewardXp: 10000,
    rewardCredits: 50000,
    rewardConsumables: { celestial_ambrosia: 1 },
    rewardTitle: 'Celestial Architect',
    badgeIcon: '👑',
  },
  {
    code: 'BATTLE_FIRST_BLOOD',
    title: 'First Blood',
    description: 'Win your first PvP Card Duel.',
    category: 'COMBATANT',
    tier: 'BRONZE',
    requirementType: 'PVP_WINS',
    requirementTarget: 1,
    rewardXp: 250,
    rewardCredits: 500,
    rewardConsumables: { potion_mana_minor: 1 },
    badgeIcon: '⚔️',
  },
  {
    code: 'BATTLE_DUNGEON_50',
    title: 'Abyssal Conqueror',
    description: 'Clear Floor 50 of the Seasonal Dungeon Tower.',
    category: 'COMBATANT',
    tier: 'GOLD',
    requirementType: 'DUNGEON_FLOOR',
    requirementTarget: 50,
    rewardXp: 5000,
    rewardCredits: 20000,
    rewardConsumables: { potion_energy_grand: 2 },
    rewardTitle: 'Abyssal Conqueror',
    badgeIcon: '🏰',
  },
  {
    code: 'BATTLE_BOSS_SLAYER',
    title: 'Calamity Slayer',
    description: 'Deal 1,000,000 total cumulative damage to Raid Bosses.',
    category: 'COMBATANT',
    tier: 'PLATINUM',
    requirementType: 'BOSS_DAMAGE',
    requirementTarget: 1000000,
    rewardXp: 8000,
    rewardCredits: 35000,
    rewardTitle: 'Dragonbane',
    badgeIcon: '🐉',
  },
  {
    code: 'CRAFT_MASTER_FORGE',
    title: 'Master of the Forge',
    description: 'Enhance any combat equipment or accessory to +10.',
    category: 'BLACKSMITH',
    tier: 'GOLD',
    requirementType: 'EQUIPMENT_ENHANCE_10',
    requirementTarget: 1,
    rewardXp: 4000,
    rewardCredits: 15000,
    rewardConsumables: { crafting_dust: 500 },
    rewardTitle: 'Master Blacksmith',
    badgeIcon: '🔨',
  },
  {
    code: 'DEVOTION_STREAK_30',
    title: 'Unyielding Devotion',
    description: 'Maintain a 30-day consecutive daily claim streak.',
    category: 'DEVOTION',
    tier: 'GOLD',
    requirementType: 'DAILY_STREAK',
    requirementTarget: 30,
    rewardXp: 6000,
    rewardCredits: 25000,
    rewardConsumables: { potion_energy_grand: 3 },
    rewardTitle: 'Unyielding Flame',
    badgeIcon: '🔥',
  },
  {
    code: 'TUTORIAL_COMPLETE',
    title: 'Journey Begins',
    description: 'Complete the Dungeon Tower Tutorial Prologue (Floors T1–T4).',
    category: 'COMBATANT',
    tier: 'BRONZE',
    requirementType: 'TUTORIAL_CLEARED',
    requirementTarget: 4,
    rewardXp: 250,
    rewardCredits: 1000,
    rewardConsumables: { potion_hp_minor: 3 },
    badgeIcon: '📖',
  },
];
