/** Guild dashboard pages, in sidebar order. Add an entry only when its page exists. */
export const GUILD_NAV_ITEMS = [
  { slug: 'overview', label: 'Overview' },
  { slug: 'general', label: 'General' },
  { slug: 'moderation', label: 'Moderation' },
  { slug: 'automod', label: 'AutoMod' },
  { slug: 'logging', label: 'Logging' },
  { slug: 'commands', label: 'Commands' },
  { slug: 'autoroles', label: 'Auto Roles' },
  { slug: 'autovoice', label: 'Auto Voice' },
  { slug: 'reaction-roles', label: 'Reaction Roles' },
  { slug: 'xp', label: 'XP & Ranking' },
  { slug: 'games', label: 'Games' },
  { slug: 'tcg', label: 'Waifu TCG' },
  { slug: 'tcg/achievements', label: 'TCG Achievements' },
  { slug: 'giveaways', label: 'Giveaways' },
  { slug: 'music', label: 'Music' },
  { slug: 'ai', label: 'AI Chatbot' },
  { slug: 'images', label: 'Image Generation' },
  { slug: 'streams', label: 'Stream Alerts' },
  { slug: 'freegames', label: 'Free Games' },
  { slug: 'welcome', label: 'Welcome Card' },
  { slug: 'farewell', label: 'Farewell Card' },
  { slug: 'integrations', label: 'Integrations' },
  { slug: 'cases', label: 'Case Log' },
  { slug: 'audit-log', label: 'Audit Log' },
] as const;
